### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by justinjk007** [jameskokoska/Cashew#106]
**Describe your question**

I have scenario, I lent money out by paying for a group using my credit card.

But when they pay me back, if I collect the loan the money goes back to my credit card.

But sometimes they might pay me back in cash or sometimes etransfer to my bank. 

How can I collect loans to different accounts and not the account I lent from?

**Comment by jameskokoska** [comment]
Great question! There are 2 ways to do this that I can think of:

1) You can change the account of the lent transaction
or
2) You can collect it then add a transfer between accounts

Edit:
Long term loans have since been introduced and solves this issue. Long term loans support the collection and lending of money from different accounts, since lending and payments will be separate transactions. See the FAQ: https://cashewapp.web.app/faq.html#loans

**Comment by justinjk007** [comment]
1, If I change the account on the lent transaction wouldn't the account I paid from be out of balance?


Would it be possible to add , Collect to a different account as a feature? 

Thanks

**Comment by jameskokoska** [comment]
Yes, you can already do this with 2 transactions via long term loans. See the Edit in my comment.

**Comment by justinjk007** [comment]
Yeah long term loan is what I kinda used at first, but if I use the Bill splitter to setup the transaction all the loans generated and one time loans and it kinda makes sense they are one time loans.


But yeah, best would be if we can collect to a different account.

You could make it so that , collection to a different account automatically adds the transfer transaction like you said?


Thanks

**Comment by jameskokoska** [comment]
Sorry this feature isn't planned as it will complicate the user experience. You can already accomplish this with long term loans, or create a transfer manually.

**Comment by rank-coder** [comment]
> To make this feature work, ideally Cashew creates a second 'payment' transaction when a loan is collected. I may rework how one time loans get paid but it introduces a lot of complications since it deviates from the current system. Maybe I can look at this more when I get the chance so there are 2 bundled transactions per lent/borrowed.

@jameskokoska and @Michael152843  Implementing at least this will be very nice. This keeps a record of when the loans get paid. Currently there is no other way than creating a partial collection. **Since it is already possible, make it less confusing.**
Since the button is called 'partially collect' a user might not figure out what they can achieve using it.



> 3\. Setting up long-term loans for simple refunds feels like overkill. Over time, you end up with hundreds of such loans, which clutters the app.

This it the reason why I was suggesting to add a way to record the loan settlement as a separate transaction. Keep it one-time loan, fine, but allow a second transaction. 
The concept will be clearer too:
1. One-time loan: Loans that are paid with a single payment
2. Long-term loan: Loans that are paid in installments, (and we know, those loans can be lent in installments as well)

**Comment by axnsan12** [comment]
'partially collect' silently makes the loan into a long-term loan. The only problem with this is that it will then appear in the "loans" section forever

I think the only change needed is make the loan stay in the "one time loans" tab, otherwise the UX is perfect (and maybe remove the "collect all" button since "partial" payment with full sum is the same thing)

**Comment by rank-coder** [comment]
> and maybe remove the "collect all" button since "partial" payment with full sum is the same thing)

I agree with this.
Removing the collect all button will solve the problem. Also make sure there is a transaction shown when the loan is settled. We need both the records.


> The only problem with this is that it will then appear in the "loans" section forever

The problem is it was not a long-term in practice, we made it a long term loan as a workaround, and that's why it's cluttering the long-term loan list. Which is problematic.
