### ISSUE TITLE
[Feature Request] Custom tags for occasions or places or sites which are used repeatedly like #birthday or #amazon

### ISSUE THREAD

**Issue by yooyoyo** [jameskokoska/Cashew#107]
custom tags which are used quite often can be added to each transaction
like tagging a place or shopping website like #Amazon or #outing

be able to choose multiple tags 2-3.
This can be added just below the notes section.

**Comment by jameskokoska** [comment]
There are no plans for tags. Cashew supports common and recommended 'Titles' which are more versatile than a tagging system. You can also filter by Titles.

Additionally, Cashew supports subcategories which are directly connected to category spending breakdowns.

**Comment by MohammadShabib** [comment]
Titles are useful, but tags would be an even better feature. Currently, I'm migrating from Spendee, which offers a tag feature.

Here's an example of why tags are more effective: 
I have a transaction for food, where I ordered chicken from Taco Bell through Uber Eats and paid using a credit card.

The transaction can be as the following:
title can be: Chicken Tags: Uber Eats, Taco Bell, Chase bank

**Comment by Michael152843** [comment]
I'm missing tags/mentions in Cashew as well. Titles can't replace them in my opinion, since Titles are like tags the other way around - you need to create a Title for every possible scenario and category, whereas with tags you would just create one tag and use it everywhere. And they could be updated dynamically, which is also handy. In short, there's a reason why they are used everywhere

**Comment by officialpiyush** [comment]
This would be a great addition to the app (whenever it will be planned), I followed what @jameskokoska  mentioned to filter using Notes, but I ran into a issue quickly, we can only filter once per tag (as it is not fuzzy search), so if I want to tag my transactions with 3 tags, for example `#food`, #card` and `#swiggy`, I'm not able to filter the transactions using only 2 tags, say for example I want to filter my "food" spending based on the delivery app, "swiggy". Categories can't be used because in most cases the categories would be something different, say for example "Spending Money", for easy budgeting.

**Comment by muhammadfredo** [comment]
> There are no plans for tags. Cashew supports common and recommended 'Titles' which are more versatile than a tagging system. You can also filter by Titles.

I don't see titles could cover my use cases below

Use Cases:

- Travel Expenses: When recording multiple category expenses for flight tickets, hotels, foods, and drinks, users can tag these expenses as "Holiday in Bali", "Holiday in Tokyo", and "Holiday in Bangkok".
- Hardware Expenses: When buying items like hard drives, users can tag them as "Work" for Workstation or "Entertainment" for Media repository while using same category "Hardware/Computer".
- Software Expenses: When buying software users can tag "Work", "Hobby", or "Upscale" and still using same "Software" as category.

When users check "Holiday in Bali" there are lots of transactions for example:
- Title= **Air Asia**, Category= **Travel/Flight** (Category/Sub-category), Note= **Flight Kuala Lumpur to Bali**, Tags= **Holiday in Bali**
- Title= **Grab**, Category= **Transportation/Taxi** (Category/Sub-category), Note= **Airport to Hotel**, Tags= **Holiday in Bali**
- Title= **Sheraton**, Category= **Travel/Lodging** (Category/Sub-category), Note= **Sheraton Hotel**, Tags= **Holiday in Bali**

Users can use the same transaction but different tags, for example
- Title= **Air Asia**, Category= **Travel/Flight** (Category/Sub-category), Note= **Flight Kuala Lumpur to Singapore**, Tags= **Business Trip**
- Title= **Hilton**, Category= **Travel/Lodging** (Category/Sub-category), Note= **Hilton Hotel**, Tags= **Staycation**
- Title= **Grab**, Category= **Transportation/Taxi** (Category/Sub-category), Note= **Office to home**, Tags= Empty


I don't see this behavior can be replicated only using Titles, at the same time cashew doesn't offer Payee as well. I don't mind if Cashew dev shut this down again.

Relying solely on Category/Sub-Category can become cumbersome and time-consuming, as users may struggle to determine the appropriate category for each expense. It often requires creating numerous categories and sub-categories to accommodate all possible expenses, leading to a cluttered and inefficient system.


Good Luck!

**Comment by ngocanhtve** [comment]
Tag are a great feature across many different types of apps, I know of a few spending apps that support tags. I also requested Cashew to support #tags but apparently the dev wasn't ready for some reason of his own.

**Comment by victor-marino** [comment]
+1 for tags.

I don't think goals are a valid solution for this either.

For instance, imagine I want to know how much I've spent on food while traveling for work.

By adding the "work" and "travel" labels to the right transactions, I can then use them to filter them super easily. I tried replicating this with notes but it doesn't work, because it can only match exact strings. So if I try to filter by notes containing "work travel", it will not show transactions where I typed "travel work", or transactions where I typed "work London travel".

Likewise, I might want to tag expenses that are related or indirectly caused by, say, having to take my kid to football practice.

I also don't understand the argument against complexity here. It's a completely optional feature, such as notes and tags. If anything, I think it would simplify the workflow of many users, as they might stop manually typing repetitive concepts in notes/descriptions if they can be appropriately entered as tags that can be selected AND filtered a lot more easily.

I honestly don't think there are much better use cases for tags than this one!

**Comment by victor-marino** [comment]
+1 for tags.

I don't think goals are a valid solution for this either.

For instance, imagine I want to know how much I've spent on food while traveling for work.

By adding the "work" and "travel" labels to the right transactions, I can then use them to filter them super easily. I tried replicating this with notes but it doesn't work, because it can only match exact strings. So if I try to filter by notes containing "work travel", it will not show transactions where I typed "travel work", or transactions where I typed "work London travel".

Likewise, I might want to tag expenses that are related or indirectly caused by, say, having to take my kid to football practice.

I also don't understand the argument against complexity here. It's a completely optional feature, such as notes and descriptions (which are a lot more involved). If anything, I think it would simplify the workflow of many users, as they might stop manually typing repetitive concepts in notes/descriptions if they can be appropriately entered as tags that can be selected AND filtered a lot more easily.

I honestly don't think there are much better use cases for tags than this one!

**Comment by victor-marino** [comment]
For the sake of completeness, here's another use case that's enabled by supporting tags:

Imagine at the end of the year, I want to know how much I've spent on food while traveling, EXCLUDING those expenses that were work-related.

In other apps that support tags and filtering by them, I can easily create a report that:
- Only includes transactions in the `Food` category
- Only includes transactions containing the `Travel` tag
- EXCLUDES transactions containing the `Work` tag

As far as I can see, it's currently impossible to create this kind of report in Cashew, given categories are hierarchical and each transaction can only belong to one category (and possibly one subcategory).

We would either need the ability to file each transaction under multiple, independent categories, or (preferably) the option to just add custom tags to them.

Could you please reconsider the tags feature? I do think this is a worthwhile addition that will heavily improve the classification and reporting capabilities of the app while barely adding complexity to the UI.

**Comment by IlianP** [comment]
I would also support the addition of tags. Just to tell you about my case:
I considered switching to Cashew from "HelloExpense" (Android) but my CSV from there contains 7% empty values for "Category" (this can be fixed before import) and 8% more than one category (this one can't be fixed, because I can't split them). As much as I love the UI/overall look and feel + features of Cashew, I want to be able to compare with my previous database.

**Comment by danielb2** [comment]
+1 for tags as well. 

> However, for the examples provided above, why not create an “Addable Budget” or a “Goal” and add transactions to that as the “tag”? This is the perfect use case to track your spending towards a trip into a budget.

I played with this solution and I found it confusing and not at all something easy to do to tag my transaction. I tried it and every single one of my transaction was suddenly added. And it's not an intuitive solution 


My use-case is that I want to know who was with me at the time, if I spent money for a particular person or whatever. Maybe my purchase was for my dog, friend, cousin, girlfriend or whatever, then i can tag their name.

**Comment by Braisrg5** [comment]
+1 for tags

As many people have already stated, it would be an useful way to add a layer of complexity and analysis to different expenses, like trips, work-related, girlfriend-related, etc. 

Also, as a way of being able to differentiate between spendings that I think were useful and others that I may have regretted as time went by. I could tag them with #proud and #not_proud or whatever.

**Comment by danielb2** [comment]
I ended up switching to another app. What I can see was very little development recently (like zero), but many excuses for not doing feature suggestions. I'd be fine to pay for the app, but not like it is now.

**Comment by RoTorEx** [comment]
> I ended up switching to another app. What I can see is that there is very little development recently (zero), but many excuses for not doing feature suggestions. I'd be fine to pay for the app, but not like it is now.

Yeah, what is it?

I partially agree with your points. I switched from Paymaster and, after trying countless other apps, decided to stick with this one and buy the lifetime. While I agree that there are some shortcomings in the UX and a lack of key features, but I still believe this project has the most potential compared to everything else I’ve tried.

I feels like the developer either doesn’t notice or chooses not to acknowledge many of our requests. This is particularly evident in how quickly some tickets are closed and the reasons given for closing them. I hope they will become more open to community feedback or even consider accepting contributions from us where appropriate.

**Comment by danielb2** [comment]
> > I ended up switching to another app. What I can see is that there is very little development recently (zero), but many excuses for not doing feature suggestions. I'd be fine to pay for the app, but not like it is now.
> 
> Yeah, what is it?

travelspend. it doesn't have a web interface tho. I thought of forking this code and implementing the features I'd like myself, but I haven't decided on it yet. So far the missing features for me are:

1. tags
2. currency selection based on GPS location
3. location tagging w/ map

**Comment by Michael152843** [comment]
+1. Highly needed feature, although I would prefer tags to be customizable with icons and colors, just like categories or titles, and usable inside notes. Half of the issues in this repository would be solved with the introduction of tags.

**Comment by hexman1999** [comment]
I wish it could be implemented

**Comment by danielb2** [comment]
I actually did end up writing my own app, and I'm looking for android testers for anyone interested. https://github.com/money-nomad/money-nomad.github.io/discussions

**Comment by oliverlalan** [comment]
I think tags solve a different problem than the existing tools, @jameskokoska. 

A title can be used to identify almost anything: a merchant, a place, a person, a project, or any other label the user chooses. That flexibility is valuable, but it still serves a different purpose than tags.

Titles, categories, budgets, and goals all describe, classify, or plan transactions. Tags create relationships between transactions that may have different titles, categories, accounts, and dates. They provide an additional dimension for organization rather than an alternative to the existing ones.

Without them, there is often no straightforward way to later answer questions such as "How much did I spend on reimbursable expenses?", "Which purchases were tax deductible?", or "What was the total cost of my kitchen renovation?" These labels can span many merchants, categories, and time periods. Neither titles nor categories are a natural fit, and creating dedicated budgets or goals for each of these use cases doesn't scale.

On complexity, the concern is fair, but scope matters. Cashew already supports optional transaction properties that users can enable or disable in the input flow, and tags seem like a natural extension of that approach. Users who do not need them could simply ignore them.

Supporting tags as a transaction property is also a much smaller commitment than building tag-based reports, analytics, and other integrations. Those could always come later if the feature proves valuable. Even on their own, tags would provide immediate value through organization and analysis of exported data.

This is also one of the most-commented feature requests in the repository, with numerous duplicate and related issues. That suggests the current model may leave a gap for a meaningful share of users.

Regardless of the outcome, thank you for building and maintaining Cashew.

**Comment by hexman1999** [comment]
I totally agree @oliverlalan

**Comment by ngocanhtve** [comment]
> I totally agree @oliverlalan

Me too

**Comment by RoTorEx** [comment]
> > I totally agree [@oliverlalan](https://github.com/oliverlalan)
> 
> Me too

I second that!

**Comment by danielb2** [comment]
> I second that!

You can't! She already did!
