### ISSUE TITLE
[Feature Request] Using currencies different from account's currency

### ISSUE THREAD

**Issue by kostiaalio** [jameskokoska/Cashew#109]
It would be great to be able to pay using a currency which is different from the account's currency. 

Let's say I have a USD credit card, and I added it as a USD account to the app. When I travel to Europe, I use this card to pay for everything in EUR, and the card payment system does the currency convertion for me automatically. 
I'd love to be able to select "EUR" currency in Cashew app when adding expense from my USD account. Ideally, it should also remember the latest used currency. 

P.S. Thanks for opensourcing an awesome app.

**Comment by jameskokoska** [comment]
Thank you for the feature request! The way currencies currently work within Cashew, it only supports one currency per account. 

However, to enter a different currency with automatic conversion into another account you can use the currency conversion button when entering an amount. 

Ensure the primary account is selected to the main currency you want to convert to, select another account when entering an amount and convert the amount back to the primary account with one tap.

See screenshot below:
![Screenshot_20231212_165246.png](https://github.com/jameskokoska/Cashew/assets/50821962/c8bc9466-d7ca-47fc-ad03-86c488cfbbfd)

**Comment by UMA1R-01** [comment]
I have gone through this thread and the official Cashew FAQ section regarding this.
But all this still does not solve the problem most of people have without the implementation of this feature.
I understand that this feature might not be on your priority list, and that's okay. But I will prefer if instead of "Closing" it, you can put this in the "Planned" issues.

Because like me, many people have to deal with multiple currencies on regular basis. So, having that currency's original value works more smoothly compared to the "conversion" as explained in the FAQ. And using this "conversion" again and again for frequent entries is a tedious process.

In case this implementation involves more workaround regarding the already-present logic for the accounts. It can be implemented as an "Optional" feature for account. That way, the ones with singular currency can remain same, and an optional category can be applied to the accounts where we might want to deal in multiple currencies.
Though I am sure you can look into much better options regarding this.

**Comment by strahb** [comment]
As @UMA1R-01 mentionned this doesn't really solve the issue. I'm doing some work abroad for a few days and both my pay and spending are going to be in Euro, my bank automatically does the conversions but that's under the hood and it wouldn't work for cash. And from what I've read there seems to be no way to account it in without creating a specific wallet for its currency.

Any plans to implement something like multi-currency accounts?
