### ISSUE TITLE
[Feature Request] Subcategories for Budget

### ISSUE THREAD

**Issue by Alien-14** [jameskokoska/Cashew#110]
This is a rather simple request. 

Currently you can only create and track budgets for a Main Categories but not subcategories. 

For example:

Main Category: Food
Sub_1: Grocery
Sub_2: Restaurant

Currently I can set a budget for "Food" but not for "Restaurant"

Is that possible to add? 

Thanks

**Comment by jameskokoska** [comment]
You can set category spending goals for subcategories and main categories. These are like budgets within budgets. You should set up your budgets accordingly.

The request is actually quite complicated to fully support subcategory only budgets. I can break it down for you: 

The main issue is that the selection progress won't make sense. For example, what happens if a transaction doesn't have a subcategory, is it included or not in the budget. This is because the subcategory is optional within a transaction.

So going off your example, if you create a budget with Grocery (subcategory) transactions, then what happens if you have a transaction with just Food (main category) and no subcategory selected. How would the user specify how to filter these transactions for a budget? 

Within Cashew you should create a Food budget and use spending limits for each subcategory. The breakdown of spending within Cashew won't be useful either as the pie chart will always contain one entry, if you want to just create a Restaurant (one subcategory) budget.

**Comment by JDKamalakar** [comment]
> You can set category spending goals for subcategories and main categories. These are like budgets within budgets. You should set up your budgets accordingly.
> 
> The request is actually quite complicated to fully support subcategory only budgets. I can break it down for you: 
> 
> The main issue is that the selection progress won't make sense. For example, what happens if a transaction doesn't have a subcategory, is it included or not in the budget. This is because the subcategory is optional within a transaction.
> 
> So going off your example, if you create a budget with Grocery (subcategory) transactions, then what happens if you have a transaction with just Food (main category) and no subcategory selected. How would the user specify how to filter these transactions for a budget? 
> 
> Within Cashew you should create a Food budget and use spending limits for each subcategory. The breakdown of spending within Cashew won't be useful either as the pie chart will always contain one entry, if you want to just create a Restaurant (one subcategory) budget.
> 
> Extra tags: subcategory budget, budget subcategory filters, subcategory for budgets

I think selection will be like this give toggle to only count sub category (as that is only that makes sense) it enabled this toggle then it will show which sub category to be tracked.

**Comment by Mendrejk** [comment]
Hi,
I think it does make sense and for example I'm pretty sure YNAB supports it.
I have a general "food" category and I have "groceries" and "dining out" subcategories within.
I would like to have the "groceries" transactions go into the "Needs" budget, and the "dining out" transactions to go to the "Wants" budget. The budget should only track transactions that have the specific subcategory assigned, ignoring all other "food" transactions. 

Or is there some other way of doing this that I'm maybe missing?

**Comment by Mendrejk** [comment]
@jameskokoska Hi, what do you think about the use case described?

**Comment by jameskokoska** [comment]
This has been added in the beta. Subcategory filters can now be applied and selected for exclusion or inclusion for "All Transaction" budgets.
If this is still an active issue, add an update and this ticket can be further discussed and reopened as necessary. See #725 for Beta Testing instructions and information.
