### ISSUE TITLE
Budget with multi-week occurrence produces incorrect date range

### ISSUE THREAD

**Issue by KiwiPolarBear** [jameskokoska/Cashew#12]
To reproduce, create a budget where the start date has a weekday later than the current weekday (e.g. start date on a Friday, while current day is Tuesday), and has a period longer than one week. You will notice that the current period will always start the week prior, not matter how many weeks have passed since the start date.

I suspect this is due to the logic [here](https://github.com/jameskokoska/Cashew/blob/fa799c05072eb8ebfe56ecc420a3811728d7788c/budget/lib/functions.dart#L502), that goes back through weekdays until it hits the same weekday as the start date. Given the if statement will hold true in a maximum of 7 iterations, the start of the current period will always be within 7 days of the current date, regardless of the number of weeks in the period.

**Comment by jameskokoska** [comment]
Fixed in https://github.com/jameskokoska/Cashew/commit/59351690ebb2ac62c4f2ffa280fcccf5cce90d30
Specifically [here](https://github.com/jameskokoska/Cashew/commit/59351690ebb2ac62c4f2ffa280fcccf5cce90d30#diff-eca24bde063a5702d757d5ef8580067d1d81124bf8f972df348cd3a1e97c787bR392)

Included weekly cycles into the existing sliding window cycle algorithm

Thank you for reporting!
