### ISSUE TITLE
[Feature Request] Budget widget (Android)

### ISSUE THREAD

**Issue by ManuelMurmann** [jameskokoska/Cashew#125]
**Is your feature request related to a problem? Please describe.**
I created a travel budget for a semi-long trip and need to open the app if i want to look at the budget. Obviously not a big problem but I created a page on my android launcher just for travel stuff and a budget widget would fit perfectly in there

**Describe the solution you'd like**
I'd love to have an android widget displaying the spent and remaining amount of a budget like the one on the home page. Then, when you click on the widget, you get forwarded to the budget overview page.

**Describe alternatives you've considered**
Opening the app

**Comment by jameskokoska** [comment]
Widgets require native code, it would require the layout to be completely rewritten just for a widget. I have gotten widgets to render using an image method, however, it didn't seem polished enough to make production.

Because of the optimized load times of the app and the ability to have a budget quick launch action already, there are no plans to recreate other components of the app in native code just for a widget.

**Comment by jameskokoska** [comment]
A widget for budgets on iOS and Android has been added to the open beta release.

See #725 for Beta Testing instructions and information
