### ISSUE TITLE
[Feature Request] - Add Extra Date and Merchant Field for Transactions

### ISSUE THREAD

**Issue by SamuelRJankis** [jameskokoska/Cashew#130]
**Is your feature request related to a problem? Please describe.**
Problem with tracking transactions clearly. 

**Describe the solution you'd like**
Ability to have additional custom fields would be ideal for future flexibility. Otherwise at the current time I would like to have one extra field for Merchant and one extra field for Return Date.  

**Describe alternatives you've considered**
Delimited titles. e.g. MerchantName - Actual title, but this obscures the real titles due to the length. 

Adding dates to the notes - Entering dates free text is cumbersome and the data is harder to identify.

**Comment by jameskokoska** [comment]
Hi there, thank you for the suggestion! Unfortunately custom fields are not planned. Extra information can be added under the notes and transactions can be filtered by notes. 

The date is already tied to a transaction, and the title can be used as you see fit (usually for the payee). 

In short, this is not going to be added because:
1) UI and usability clutter 
2) Ideally each field should be a new column in SQL, and customizing the table at runtime isn't possible in the current architecture.
3) Notes can be used instead and can be used as the user sees fit. They are more versatile in that sense. Transactions can be filtered by notes and titles already.

**Comment by SamuelRJankis** [comment]
Hello,

Just to add some feedback for your alternatives.

1. Unnecessary UI elements can be automatically hidden if they're not used.
2. The ah-hoc custom field was a very ideal scenario. I'd be very happy with a additional date and merchant field.
3. Since a Merchant field would be used for 95% of my transactions manually entering in the notes section appose to a drop down would make quite a usability difference.
