### ISSUE TITLE
[Feature Request] Add overspent to next budget

### ISSUE THREAD

**Issue by victorbnl** [jameskokoska/Cashew#134]
**Is your feature request related to a problem? Please describe.**
If I overspent 30€ one month, I would like the app to make me spend 30€ less next month in order to balance it.

**Describe the solution you'd like**
I would like the app to either (preferably) start at 30€ spent, or automatically set the budget to 30€ less the next month.

**Describe alternatives you've considered**
Manually adding the overspent amount as a transaction on the first day of the next month.

**Comment by jameskokoska** [comment]
Budgets are meant to reset each period and this is the way budgets are always intended to work within this app. No plans to add in carry over totals as it creates an infinite loop of past period totals for calculations.

This is a good suggestion, however, each budget period's total will need to be calculated, and the one before, and the one before etc and you can see how it's an issue. I think it's important to set a budget limit that works for you for each period. If you go over a bit, or spend under a bit, try to correct or adjust your total in the new period. This encourages healthy consistent spending habits.

Edit: You can always increase your budget time period and increase your total limit. For example, if you want 30€ per week, consider setting 30€ * 4weeks = 120€ per month budget instead. You can even increase it to a yearly budget if necessary and correct the total every year as needed. This will also give you a better overview of spending progress throughout a long time period.
Cashew also allows you to exclude major transactions from certain budgets. This can help you split up your spending so that outlier purchases can be excluded from normal spending budget habit tracking.

Alternatively, you can create a custom budget period with an adjusted budget total for each period of interest. Cashew allows for various use cases given its current implementation of budgets. This is related to this issue: https://github.com/jameskokoska/Cashew/issues/335#issuecomment-2233121150
This is also documented in the FAQ: https://cashewapp.web.app/faq.html#budget-period-amounts

Extra tags: rollover, roll over, carry over, carry balance, overflow, over flow, carry forward

**Comment by Radwan-Albahrani** [comment]
I think there would be an alternative to an infinite loop. Instead of counting the previous budgets, add the amount for the next budget.

So for example, I have a budget of 200$

I spend 300$

this makes the offset or overspent amount -100$

next budget, add 200
-100$ + 200$ =$100.00 

say I spend nothing that week

on the reset day the offset amount would be 100$

100$ + 200$ =$300.00 

this would actually have a workaround by instead making an account with a weekly scheduled transaction of 200$ or whatever the budget amount is. That way there is no infinite loop. 

This makes the feature hopefully much easier to implement. 

@jameskokoska

**Comment by johanjohnthomas** [comment]
Hi @jameskokoska  - may I ask why this isn't a planned feature? I agree that it is a bad habit to allow for overflow carrying forward, but underflow carrying forward can only encourage better budgeting for larger purchases.

there seems to be traction for this feature based on the previous feature requests, and the solution proposed by @Radwan-Albahrani  is low cost to implement as well.
