### ISSUE TITLE
[Bug] Biometric authentication prevents app from being loaded if not available when restoring backups

### ISSUE THREAD

**Issue by Grabstertv** [jameskokoska/Cashew#139]
**Describe the bug**
Restoring a backup on Android results in blank screen with blank a clickable overlay that cant be bypassed.

**How to reproduce**
- Create a backup on another device
- Reinstall cashew on android, login
- Restore the last backup
- Restart the app

**Screenshots/videos**
https://github.com/jameskokoska/Cashew/assets/49114212/3e14cb22-1c82-422d-9234-93937c84b14d

**Details**
 - Device: Samsung Galaxy A03
 - App Version: 5.1.9

NOTE TO THE SUBMITTER
Reporting bugs is important for maintaining the app. Thank you for helping make the app a better experience for all!

**Comment by jameskokoska** [comment]
This screen shows up when it is waiting to authenticate using biometrics. When you tap the screen, Cashew should be asking your OS for information on your biometric authentication on your device. Seems like Cashew cannot get this information. I can look into removing biometric authentication if not available. However it will be difficult for me to test because this is an OS/device specific issue, so no guarantees on a fix.

It seems that upon first login, Cashew also fails to import your sync backups. Can you provide some more information of what is listed under the 'Sync' popup section in the Google Login Backup page.

**Comment by Grabstertv** [comment]
I see. This makes sense because the phone does not have any biometric sensors. Cashew gives an error when enabling it before backup. Hope this can be fixed for phones like this.

The sync page you asked for contains the usual devices i last logged into. In this case my Macbook, iPhone and the Samsung I'm using.

**Comment by jameskokoska** [comment]
Ah thanks for the details, can you provide some more information about the error Cashew shows when biometrics are attempted to be enabled on a device without biometric sensors?

**Comment by Grabstertv** [comment]
"There was an error using the devices biometrice"

**Comment by jameskokoska** [comment]
Should be fixed here: https://github.com/jameskokoska/Cashew/commit/4f5bb5f69aca5f044528ebd4d8db1fb499aecd5e#diff-39d5af616101455b99fe8c9abd851b17f836bfcbfbd160903f46fb635eaf050aR17-R36

Closing for now, let me know if the issue persists
