### ISSUE TITLE
The spent percentage of categories has incorrect values

### ISSUE THREAD

**Issue by JeanJPNM** [jameskokoska/Cashew#14]
The percentages of categories in the expense/income pie chart in the wallet details page are distributed incorrectly when using subcategories:

![image](https://github.com/jameskokoska/Cashew/assets/61994401/3ce70857-f8b3-4678-9111-8d1ec521244f)

Steps to reproduce:
- Create one category that has one subcategory
- Create a transaction that belongs to that subcategory
- Create a transaction that belongs to that category, but not to the subcategory
- Check the account details page
- Check the percentages bellow the pie chart

It appears that both the main category and subcategory are adding their spent amount to the total amount spent, despite the fact that the main category's spent amount already includes all of its subcategories.

I suspect the bug originates from [here](https://github.com/jameskokoska/Cashew/blob/fa799c05072eb8ebfe56ecc420a3811728d7788c/budget/lib/struct/spendingSummaryHelper.dart#L57-L62)

**Comment by jameskokoska** [comment]
Fixed in https://github.com/jameskokoska/Cashew/commit/59351690ebb2ac62c4f2ffa280fcccf5cce90d30
Specifically [here](https://github.com/jameskokoska/Cashew/commit/59351690ebb2ac62c4f2ffa280fcccf5cce90d30#diff-58afb9f76317ffbeccb11a2fe6b8472eaa08409c5b2522b8e25f11309ef78479R263)

Also changed it so that subcategories show the percentage spent within the main category instead

**Comment by jameskokoska** [comment]
Fixed in https://github.com/jameskokoska/Cashew/commit/b1fd5634133acf7b693524f2dd4e060e4155007b [here](https://github.com/jameskokoska/Cashew/commit/b1fd5634133acf7b693524f2dd4e060e4155007b#diff-58afb9f76317ffbeccb11a2fe6b8472eaa08409c5b2522b8e25f11309ef78479L87)
Redefined the definition of percentage spent
