### ISSUE TITLE
[Feature Request] Forgiving Debts and Loans

### ISSUE THREAD

**Issue by mysticmist-git** [jameskokoska/Cashew#146]
**Problem:**

Currently, Cashew does not have a way to mark debts or loans as forgiven. This can create issues in the following situations:

**Informal loan forgiveness:** It's common for friends or family members to lend or borrow small amounts without expecting repayment. In these cases, both parties may agree to forgive the debt, but Cashew still tracks it as an outstanding balance. This can clutter up the debt/loan summary and make it difficult to get an accurate picture of one's true financial situation.
**Partial loan forgiveness:** Sometimes, lenders may agree to forgive a portion of a loan as a settlement or due to extenuating circumstances. Again, Cashew doesn't currently have a way to reflect this change, leading to inaccurate record-keeping.

**Proposed Solution:**

**Simple forgiveness button:** Add a button next to each debt or loan item that, when clicked, marks the debt as forgiven and removes it from the outstanding balance calculations.
**Partial forgiveness option:** Allow users to specify an amount of the debt that is being forgiven. This would update the remaining balance and keep a record of the forgiven amount.
**Forgiveness reason option:** Optionally, allow users to select a reason for forgiving the debt (e.g., gift, settlement, etc.). This information could be useful for tracking trends or understanding personal financial habits.

Thank you for your time and consideration.

**Comment by jameskokoska** [comment]
Hi thanks for the suggestion!  The way Cashew understands one time loans as outstanding, they are 'paid' internally and get set to unpaid. An unpaid loan is read as an uncollected loan. Skipped loan transactions can be treated as a forgiven loan. 

However, if this was implemented for one time loans, implementing this for long term loans for usability consistency doesn't make sense. Since long term loans track the difference, a forgiven amount will balance out to zero, equivalent to that of settling a long term loan.

The best solution would be to delete the one time loan, or never mark it as settled.
