### ISSUE TITLE
[Feature Request] widgets for iOS app

### ISSUE THREAD

**Issue by PakaVishwaTeja** [jameskokoska/Cashew#148]
**Is your feature request related to a problem? Please describe.**
it will be easier to add transactions if we have a widget which we can place on Home Screen on apple devices

**Describe the solution you'd like**
iOS widget

**Comment by jameskokoska** [comment]
Thanks for the suggestion! Unfortunately because this is a native feature and I don't use a Mac as a main dev environment, it's difficult for me to implement and test native iOS features. For now, quick actions are supported for quickly adding transactions (long pressing the app icon on the homepage)
