### ISSUE TITLE
[Feature Request] Drag the scroll bar to reach the bottom of the search results list

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#167]
**Is your feature request related to a problem? Please describe.**
Search results (sometimes transactions from filtering) can have dozens to hundreds of transactions, a very long list. To quickly reach the end of the list, there is currently only one way: swipe up the transactions, swipe up many times and for quite a long time. What if there are thousands of transactions?

**Describe the solution you'd like**
Drag Scroll bar - a popular and extremely useful feature since Jurassic period :D 

It will help quickly scroll through parts of the list. The current scroll bar only functions to help visualize the position you are standing in or the length of the list.

**Describe alternatives you've considered**
There is now a “go to top” button, I wouldn’t mind a “go to bottom” button, it would be extremely useful.

**Additional context**
In case you're wondering why I want to go to the bottom of the search results list. At the end of the list there is useful information such as total cash flow, number of transactions, and period of those transactions. As well as see how the earliest transaction on the list looks like...

**Update**
I just discovered that the scroll bar of the default messaging application on Android is very useful in that it displays the time when dragged to a certain location to help locate the time of the message at that location.
![](https://i.imgur.com/Fb89i94.png)

Transactions in Cashew's case, like that messages, are also tied to a specific time, and if the scroll bar can also be visually displayed like that, all the better.

**Comment by jameskokoska** [comment]
Thank you for the suggestion! Unfortunately since items are loaded dynamically into the lists, the scrollbar isn't aware of how long a list can be. Enabling drag to scroll would create unpredictable scrolling behavior.
I feel like the information at the bottom of the list, such as cash flow and time period is better represented on other pages, such as the All Spending page.

However, I have added a scroll to bottom button on the search transactions result page. This scroll to bottom button will only appear if the list is within a certain length limit though, as scrolling through a very long list to the bottom is very slow processing.
Added here: https://github.com/jameskokoska/Cashew/commit/a61cb37133fd8cc7c7a90892431ac11b908cb60d#diff-cb0c87c418ebc3616ab4975f56a75f7075e4357e12566ed79f610fa36c7159dc

**Comment by ngocanhtve** [comment]
> However, I have added a scroll to bottom button on the search transactions result page. This scroll to bottom button will only appear if the list is within a certain length limit though, as scrolling through a very long list to the bottom is very slow processing.
> Added here: a61cb37#diff-cb0c87c418ebc3616ab4975f56a75f7075e4357e12566ed79f610fa36c7159dc

Works in latest update. Thanks for your great work!

**Comment by ngocanhtve** [comment]
It seems that if the transactions is ≥ 1200, the scrolltobottom button will disappear. Why is there this limit?

**Comment by jameskokoska** [comment]
It's an unfortunate performance limitation. Consider decreasing your date range to limit the amount of transactions shown
