### ISSUE TITLE
[Feature Request] Option to select all transactions from search results

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#168]
**Is your feature request related to a problem? Please describe.**
Once I filter out about for example 50 transactions by specific keywords to add them to a long-term loan. Or to change the category, change date or change account for all 50 transactions. Selecting a large number of transactions takes a lot of operations. 

**Describe the solution you'd like**
A “select all button” option!

**Describe alternatives you've considered**
I haven't thought of it yet.

**Comment by jameskokoska** [comment]
Because the app bar is a separate entity from the transactions list, it is unaware of which transactions are currently listed. I have however managed to implement a work around, but it took some thinking on an efficient way to accomplish the task. Added here: https://github.com/jameskokoska/Cashew/commit/39489183f7a7a774f447057e9214b2e8607a986e

**Comment by ngocanhtve** [comment]
The **select all** button has implemented, thank you.
