### ISSUE TITLE
[Feature Request] Jump button to jump to the oldest month on the transaction page

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#169]
**Is your feature request related to a problem? Please describe.**
On the transaction page, when i swipe right to go to months before the current month, a button on the right side will appear to “back to the current month”. 

But if I want to go to the oldest month before, I have no choice but to keep swiping and swiping, and I don't know exactly which month in my database is the oldest month.

Constantly swiping forward like that took me to the months and years before I was even born, there were certainly no transactions at that time, so there was no need. Instead let's limit it to the oldest month of transactions in my database.

**Describe the solution you'd like**
A button is like a “back to the current month” button, but now it will have the ability to go to the oldest month.

**Comment by jameskokoska** [comment]
Thank you for the suggestion! From a usability standpoint it's a pretty niche feature to automatically scroll to the first month containing the first transaction entered into the app. Because of this reason, it will create unnecessary UI clutter. However, I have made it so that the months cannot be scrolled past the transaction date of the first entered transaction that exists in the database. Added here: https://github.com/jameskokoska/Cashew/commit/a834e4795e317263f103c1af7aebe3de9a2137bc

**Comment by ngocanhtve** [comment]
> However, I have made it so that the months cannot be scrolled past the transaction date of the first entered transaction that exists in the database. Added here: a834e47

Working on latest update 5.2.6! 

While not implementing a button to access the first month in the database, it has also been implemented to identify the first month by scrolling through the months. Still a useful implementation. 

Thanks for the great work!
