### ISSUE TITLE
[Feature Request] Total expenditure for a specific category and subcategory

### ISSUE THREAD

**Issue by szulcDEV** [jameskokoska/Cashew#173]
**Is your feature request related to a problem? Please describe.**
Add a feature in 'All Spending' to switch to a view of the total sum for each category and subcategory. This means calculating the sum of both outgoing and incoming balances to determine if the balance for a given category is positive or negative.

Example:
If your expenses for transportation are 300 (outgoing) and you received 150 from carpooling (incoming), the category's balance would be -150.

**Describe the solution you'd like**
Add a button next to or below 'Outgoing' and 'Incoming' in the 'All Spending' tab.

**Comment by jameskokoska** [comment]
Hi there! Thanks for the feature request. Unfortunately the way the pie chart and spending category section works is that it only includes transactions of the same polarity. For example, if a category is of -150 and 150 in the same pie chart, the pie chart would display totals incorrectly (since the sun should be zero). For this reason, transactions of different polarities have been separated into tabs (incoming and outgoing)

**Comment by szulcDEV** [comment]
In such a case, wouldn't it be possible to disable the pie chart? - In my opinion, this feature could be useful for many users.

**Comment by jameskokoska** [comment]
I can add it to my list, however I'm still going to think it through so so promises. Therefore, I will keep the ticket closed for now. Maybe a bar chart representation would make more sense. This would require some work though. The way Cashew is designed is to separate income and expense categories, however, not enforced.
