### ISSUE TITLE
[Feature Request] Assign functions to double-tap the buttons in the Bottom bar

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#176]
**Is your feature request related to a problem? Please describe.**
We can now double-tap the **Home** button on the bottom bar to return to the top of the Home page, double-tap the **Transaction** button on the bottom bar to start searching. How about **More, Loans or Budgets** buttons?

**Describe the solution you'd like**
- Assign the function of the **Settings & Customization** button to double-tap the **More** button on the bottom bar. This means that tapping the **More** button once will access the **More Action** page, double-tapping will directly access the **Settings & Customization** page. I think accessing the Settings will be extremely quick now.

- As for the **Loans** button on the bottom bar, I suggest tapping it once will go to the Loans page, Pressing again will switch between **All, Lent, Borrowed** tabs.

**Comment by jameskokoska** [comment]
Thanks for the suggestion! From a usability perspective, I don't think it makes much sense to include a double tap action for each page. Additionally, if a user accidentally double taps a bottom button (accounting for accessibility) then they may become navigationally confused.

Since the Settings and Customization page isn't necessarily the primary action on the More Action page, and Settings are not necessarily something that needs to be accessed/changed all the time, it doesn't make much sense for a double tap to open this page. Additionally, I don't think it makes much sense for the loans page to toggle between sections when tapped for a second time.

However, I have implemented it so long pressing the homepage navbar icon allows the user to edit the homepage here: https://github.com/jameskokoska/Cashew/commit/681ad73ec8ef98d754ec2e7c1062b9837cd01089
