### ISSUE TITLE
[Feature Request] Interest amount paid for the Loan

### ISSUE THREAD

**Issue by RakeshRafter** [jameskokoska/Cashew#182]
**Is your feature request related to a problem? Please describe.**
Yes, usually the bank the loan we are getting will always have interest to be paid with the principle so if we have an option to add principle and interest separately for loan would be nice.

**Describe the solution you'd like**
When adding a loan transaction there must be a additional option to add interest which can be tracked separately

**Comment by jameskokoska** [comment]
There are 2 ways to do this within Cashew.

A long term loan supports an offset amount, which can be the total interest. Once a long term loan is added, you can edit the offset by editing the long term loan. It is recommended to use this option as a separate transaction is not needed. (See the FAQ: https://cashewapp.web.app/faq.html#lt-loans)

Alternatively, you can add a 'Paid' transaction for a loan to account for interest. This is because it will increase the total amount of the long term loan, which will need to be paid back eventually. If you do not want this transaction to count towards your account total, see: https://cashewapp.web.app/faq.html#set-budget-no-change-balance

![Screenshot_20240318_093634.png](https://github.com/jameskokoska/Cashew/assets/50821962/e4da742e-9eb8-405b-a032-0a70ce0341f6)


Automatically adding interest rates based on a percentage is out of scope of this application. This application should not be used for tracking investments and accurately identifying interest rate percentages. Another application or Excel sheet would be a better solution for accurately tracking this information. If you wish to use Cashew, you will need to manually input any changes in amounts.

As a related aside:
To add interest as a line item in an account, you can make use of a balance correction type transaction or a income type transaction (since interest would be a positive cash flow)

**Comment by RakeshRafter** [comment]
Hi James,

I get your point on these but wouldn't be nice if we have a feature of
adding interest for every month? so that we can keep track of everything

Thanks

**Comment by berengerzyla** [comment]
Hi James! Hello from QC!
First of all, congrats on this amazing app. I've been looking into a new home from Money Pro, and I think I found it.
(I know you write in the README that you don't want to mess with PR and money, but I'd be willing to help, free of charge. I'm myself in the dev world, and having a child, things always happen on the -little- free time).

Anyhow, I read the many opened&closed issues related to this topic of loans & interest, and would like to weight in.
Many budgeting apps have this. Even if not to track the interest paid, much less calculating it, but when importing the monthly reports from the bank, having the interests taken into account helps in many ways. I have read the several workarounds that you mentioned and the ones in https://github.com/jameskokoska/Cashew/issues/256 but they all involve making unwanted changes to the total balance of the loan, or several extra steps.

Without having a tracker for the interest paid, or calculating the interest within the app, the option to enter separately the interest amount and the primary amount could help everyone (in the tickets I read).
The total amount could be read-only, and would be the amount applied in the transaction against the amount. The interest would be unused, and only the primary amount would be applied against the balance of the loan. It's this double-data (primary vs total) that's the key to tracking loan repayments.

Example:

<img width="1026" height="635" alt="Image" src="https://github.com/user-attachments/assets/f6f3db8c-b2eb-45aa-b558-42aef557b730" />

Again, willing to try to help with some code, if you were to want some help.
Have a great end of 2025!
