### ISSUE TITLE
[Feature Request] Set a budget or goal that does not change my account balance

### ISSUE THREAD

**Issue by Pkcarreno** [jameskokoska/Cashew#185]
**Is your feature request related to a problem? Please describe.**
I want to keep track of my emergency fund, but I have no way to put it into a budget without modifying my account balance, and I want the account balance to reflect my actual account balance so I know I haven't missed any transfers.

**Describe the solution you'd like**
when excluding a transfer assigned to a budget, it should be reflected in the budget but excluded in the rest of the app. 

**Describe alternatives you've considered**
I also thought that it could be a budget option, not modifying the balances, and running in parallel as if it were an "excluded account" but I don't know how feasible it is to develop it.

**Additional context**
the idea is to be able to have independence between "the amount that comes in" and assigning it to the different budgets, and not having to fix a complete income to a budget, which at the moment of distributing it generates a fictitious flow of money that affects the statistics.

Note: Thank you for this amazing app, it is by far the best I have used to manage my finances, I appreciate the effort behind it.

**Comment by jameskokoska** [comment]
Thanks for the suggestion! This is a difficult issue to solve because it would be implementing an unintuitive reverse way of thinking about ignoring funds (i.e. the opposite of what is currently implemented as ignore totals). Ignore amount usually implies it should be ignored from everything, however you would like it to count towards only some totals. Because of this, it's a difficult usability implementation, so I would suggest using the method below.

I think the best way is to use a separate account. Track the total amount added to that account separately - which will not count towards the actual balance total you want (Since you can select the accounts in your net total calculation). Then assign a budget to only track the balance from that separate account. 

Hopefully this help, closing the issue for now but feel free to continue the conversation.
