### ISSUE TITLE
[Question] Transfer between "Loans" and "Accounts"

### ISSUE THREAD

**Issue by Aravind-Ram-321** [jameskokoska/Cashew#195]
**Is your feature request related to a problem? Please describe.**
Normally when we get a loan from a bank, a separate loan account with a unique account number gets created and the amount is deposited in that account by the bank initially. Then the borrower will have to transfer the required amount from the loan account to to their personal savings account. I'm not sure if this is the process for all kinds of loans but this is what I had to do for my educational loan. Now when I want to capture these loan transactions in my Cashew app, I'm unable to transfer amount between the app's "loan" feature and the app's "account" feature (which is where my savings accounts are added)

**Describe the solution you'd like**
When adding a "transfer" record/transaction, make it possible to be able to select the loans in the from and to account selection lists.

**Describe alternatives you've considered**
For now I'm considering to add my loan account as a new "account" instead of a "long term loan" in the app so that I will be able to transfer amounts between my savings account and loan account.

Thanks for all the great work!

**Comment by jameskokoska** [comment]
Once a transfer is created between accounts, the outgoing or incoming transfer transaction can be added to a long term loan.

The alternative you've described is the only way to transfer an amount into a loan that doesn't count towards the total of your primary account. Since each transaction requires an account, it will always count towards your main total.
