### ISSUE TITLE
[Feature Request] Sub Accounts

### ISSUE THREAD

**Issue by Eggroley** [jameskokoska/Cashew#197]
**Is your feature request related to a problem? Please describe.**
It becomes very cluttered when I'm forced to create a new account for each checking, credit card, or savings account. Having a simple overview of each category is impossible.

**Describe the solution you'd like**
I'd like to see sub accounts. I interpret this as the ability to have one main account ex: credit cards, and have each sub account be each credit account. Or as another example, say you have two checking accounts. Instead of listing them under separate accounts, you can put them under one main account to keep it less cluttered.

**Describe alternatives you've considered**
At the moment, I've opted to add up the balances of all my accounts and combine them into one main account. This isn't very satisfactory as I can't specify which credit/bank was used for transactions and I can't get an advanced overview of those individual accounts because it doesn't exist.

**Comment by jameskokoska** [comment]
Hi there, thank you for the suggestion! Unfortunately, I don't find that sub-accounts makes much sense in terms of usability and organization. Since each account stores it's own total separately, separating the statistics into multiple totals would be confusing (Since the main category would still have its own total sum of all its sub-accounts). Additionally, it creates many more user interactions when selecting an account for a transaction.

The best solution would be to create a separate account for each account type you have. If you need a total summary of certain accounts, you can select the accounts via filters in the All Spending page, filters are also saved across sessions. Compared to sub-categories, sub-accounts don't intuitively fit well.
