### ISSUE TITLE
Dynamic budgets (budget of x% of income)

### ISSUE THREAD

**Issue by lovfi** [jameskokoska/Cashew#198]
**Is your feature request related to a problem? Please describe.**
My monthly income is highly variable, and thus it's hard to set reasonable saving budgets of fixed amounts. I find myself having to make new budgets every month based on my earnings, which feels like extra hassle. 

**Describe the solution you'd like**
Allow setting budgets that are x% of your income for that time period. In practice, every time you get income from a selected category, the app would add 50% of that income to the budget for the set time period (monthly, yearly, etc.).

**Describe alternatives you've considered**
Only what I've already been doing, which is creating a new budget for every month, or editing ongoing budgets.

**Comment by jameskokoska** [comment]
Hi there thanks for the suggestion! The way the app functions at the core, it expects a fixed amount. It's difficult to introduce dynamic budget amounts because the app wouldn't know to take your income from the current period, previous period, etc (as income can also come in at different times). It's recommended to create stable budgeting habits, or adjust as needed when things change. As you mentioned a budget per custom period with a custom amount is also a viable option - since Cashew has support for many use cases.

**Comment by 666f78** [comment]
Maybe you can add a possibility to calculate the percentage of income sum in this moment?
moment - when you create or edit budget
