### ISSUE TITLE
[Feature Request] Long-term loan hide button at its edit page

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#199]
**Is your feature request related to a problem? Please describe.**

I realized that every time I have a settled long-term loan and want to hide it, I have to scroll to the top of the loans page and press the edit button, then search/scroll to that loan again to click the hide button (eye button). 

The issue is that it is too cumbersome, only suitable when i want to hide multiple loans at the one time. Another inconvenience is that when at that _hide loans page_, only the names of the loans are showing without any information about the numbers, i'm temporarily lost as to which loans are settled and need to be hidden.

For real use situations, a more direct way is needed!

**Describe the solution you'd like**

While viewing a loan, long press on it to edit, please add a hide loan button next to the delete loan button. On the _hide loan page_, the hide button and delete button are right next to each other. Also on the separate edit page for each loan, the same would be extremely reasonable.

**Describe alternatives you've considered**
...

**Additional context**
![](https://i.imgur.com/mnopmUQ.jpeg)

**Comment by jameskokoska** [comment]
The reason the hide button is in the edit page, is so the user is aware of its disappearance. It fades away indicating it's action. If it's in the edit page, leaving the edit page will confuse users about what happened when they pop up the navigation stack and it is no longer listed. Even providing feedback such as 'Loan hidden' or 'Loan archived' when the action is taken is still not obvious since there is no immediate feedback of the action's doing.

Just because an action seems more convenient doesn't necessarily mean it is intuitive. Especially since Cashew keeps guides of user interactions to a minimal.
