### ISSUE TITLE
backups improvement

### ISSUE THREAD

**Issue by krzemyczek** [jameskokoska/Cashew#20]
1. password protected backups into google (it would be nice to know that google has only information about size of file and no of all our transaction. The reason why i consider this app and why i so much it to be better is by the fact that it's open source. And sending your unencrypted backups to google little destroy the idea)

2. Regular local backups (Allow users to choose between frequency of this)

I hope you consider my request!

**Comment by jameskokoska** [comment]
Hi thanks for reaching out! Google handles the file transfers internally via the Google Drive API. Since it is all stored internally in your drive, it isn't accessible by others. I'm not sure how the traffic works in transit when using the API, but it most likely uses HTTPS for encrypted traffic. 

Encrypted backups themselves are not planned, as it complicates the backup and restore process. 

Automatic local backups and frequency will not be implemented as it can clutter the users local files. Auto delete of local backups (to keep the last few) complicates the trust of file management. For auto backups, consider using Google Drive.

**Comment by krzemyczek** [comment]
> Hi thanks for reaching out! Google handles the file transfers internally via the Google Drive API. Since it is all stored internally in your drive, it isn't accessible by others. I'm not sure how the traffic works in transit when using the API, but it most likely uses HTTPS for encrypted traffic.

I'm sure that it  i s  secure while sending to google, but then google has access to your files and that's the problem for me and 2 other people there

**Comment by jameskokoska** [comment]
I understand. If you are afraid of privacy regarding Google, you can use the local backup feature. However, since the app is based around the Google login and Drive backup, you will get the most features from using it.

**Comment by krzemyczek** [comment]
> Automatic local backups and frequency will not be implemented as it can clutter the users local files. Auto delete of local backups (to keep the last few) complicates the trust of file management. For auto backups, consider using Google Drive.

you know in simple calendar, contacts and so on, there is option to use automatic backups, and it occupadies little space that it doesn't matter. My whole 2 years transaction in .csv files have less than 200kb. And it be up to user to choose if they want to enable it or not, and for me it would be easier and savier not to lose some data

**Comment by jameskokoska** [comment]
Keep in mind this app is not trying to replace other apps. If other apps suit your needs better, feel free to use them instead :) 

This app uses SQL to save data instead of CSV.

**Comment by Ansem93** [comment]
Hi,
since I'm having the same issue can I ask about two things?
1) Can we choose a folder for cashew backup? Download is not really the best place where to put a file
2) "Automatic local backups and frequency will not be implemented as it can clutter the users local files. Auto delete of local backups (to keep the last few) complicates the trust of file management." -> If we can choose a folder that it would be really easy to just delete the older files. Imho it wouldn't even be necessary witha default settings "weekely backup", it could take years before the space would be noticeable.

**Comment by jameskokoska** [comment]
Just gonna add a few more points: Android file system permissions are very wonky. Cashew aims to support all devices, and to do so it saves the file to the downloads folder by default, however if an error is thrown (because a lack of file permissions or device limitations) the new API is called which asks the user to select a folder and allow permission at that instance in time. This behaviour is the only way local backups work on iOS. 

Because of these limitations, Cashew cannot guarantee access to a folder for automated local backups (unless it has the possibility to ask the user every single time for a folder to save the scheduled backup at). This isn't a good implementation of an automated backup system and is an unfortunate limitation of Android OS. The app has its own local file system, however it is inaccessible by the user. This is where Cashew stores it's database. It is a guarantee that the app always has access to this folder, however if the app is uninstalled this data is deleted which makes local backups pointless in that sense (unless data loss occurs during an update to the DB or read/write - which is very unlikely. The only such case would be if a migration fails - but this won't actually corrupt any data it will just fail to load the db and it can be fixed with another fixed migration attempt)

**Comment by ngocanhtve** [comment]
> Cashew cannot guarantee access to a folder for automated local backups (unless it has the possibility to ask the user every single time for a folder to save the scheduled backup at).

Aegis can do this. Just initially set up a folder specifically for Aegis backups, and grant permissions, Aegis will automatically back up to that folder every time there are any data changes.

The open source applications I use mostly work that way, they don't support Google Drive backup, they're completely offline. They should be forced to have the ability to back up to a pre-selected folder.

**Comment by Ansem93** [comment]
The same goes for audiobookshelf. It's an open source app available on both android and ios. It ask the permissions to access a folder and then it can save/delete all audiobooks without issue.

**Comment by PrestigiousBeat6355** [comment]
Something similar to note taking app joplin can be implemented here i guess, it uses webDAV to store encrypted data to various services like Next cloud, Onedrive, drop box etc.

**Comment by Der-Flip** [comment]
Hi,

So while im super happy with cashew this topic is what bothers me a tiny bit.

To be honest I'm not quite sure I'm with you here.
Plenty of apps (fossify, aegis, syncthing, blood pressure monitor, or if we're talking not strictly Foss obsidian) manage auto backups either on a timely basis or on a onChange basis.

I'm. It quite sure further I understand your argument on the limitation of Android, but that's just a side note here.

While I appreciate the manual Back-up, it does keep me from having regular backups. I'm not going into the settings every week to export a backup. The way it is now it's basically just for migration but not for having continuous backups in case of loss of device for instance. Having a dedicated folder Cashew dumps a weekly backup in could be synced using syncthing or any other preferred file syncing service (owncloud for instance).

As a compromise I could imagine a prompt after [recurring user-defined time] could work. Like
```
do you want to create your weekly Back-up now?
[ ]Yes
[ ]remind me later
[ ]cancel
```
 and if the user taps `Yes` the Back-up is created the same way it usually is by using the manual Back-up in the settings.  
It would be nice to be able to define a folder to which the backup is saved by default in the settings and should the permission have expired / nuked itself for some reason, then the familiar process is being started.

**Comment by KAGEYAM4** [comment]
is there intent command that can be used to trigger local backup through Tasker?
