### ISSUE TITLE
[Feature Request] e2e data encryption

### ISSUE THREAD

**Issue by quentincaffeino** [jameskokoska/Cashew#200]
**Is your feature request related to a problem? Please describe.**
e2e data encryption

**Describe the solution you'd like**
to avoid accidental data leakage it would be nice to have this as a baked in feature

**Comment by quentincaffeino** [comment]
Found the duplicate myself #20

**Comment by quentincaffeino** [comment]
I love the ui, but options for tech-savy users are really lacking. I wish there'd be more. Is it possible that if there'd be enough traction more advanced features will be implemented or is this app feature set limited by design?

cc @jameskokoska

**Comment by jameskokoska** [comment]
Closing since duplicate was found.

**Comment by jameskokoska** [comment]
Cashew actually offers a variety of options that are generally considered only understood by tech-savvy users. Additionally, given this app is open source, you are also free to explore the code and core functionality of how the app works and tweak it to your needs.

## Advanced Features

### App Links (Automatically Add Transactions)

One example would be App Links. In summary, App Links allows for the **automation of the addition of transactions**. One such use case would be to link it to your bank or notifications to generate an app link, write a custom script, or create a custom GPT (AI chat) to generate a link based on given params. You can check out the documentation in the README here: https://github.com/jameskokoska/Cashew?tab=readme-ov-file#app-links App Links are supported by Cashew.

## Debug (unsupported) features

Cashew also contains hidden debug features (however most are functional, just not fully supported yet). Most features end up here while in testing before release, or never make it to mainstream because of their complex nature. These features are not fully supported!

_To access debug features, head to [About] > long press [Cashew] app name. This will open the 'Debug' menu._  

### Read Notifications

One such debug feature includes **automatic transactions based on notifications** i.e. [Notification Transactions]. Support is limited and Cashew only reads notifications while the app is open. Once a template is set up, Cashew can automatically prompt transaction insertion with prefilled information from a devices notification (Android only). 

### Long term 'people' tag loans

Another debug feature that could be useful is **people loans** [Long Term Loan Differences]. Once enabled, long term loans now has the option to be a timeless loan. (Create a new long term loan and enable the timer icon) This is useful if lending money to people back and forth over long periods of time. If the amount is over/under Cashew calculates the total of what is owed/required to pay back.

### Graph Options

There are also many graph options such as [Use Cumulative Spending] and [Hide Zero Transactions] that manipulate the way graph points are displayed and calculated.

---

Keep in mind the debug features listed here are not supported and I will not provide any insights into it's usability past this. There is no documentation and instructions past what is explained above (and what is available in the UI when using the feature) and the underlying code itself.

**Comment by quentincaffeino** [comment]
> Additionally, given this app is open source, you are also free to explore the code and core functionality of how the app works and tweak it to your needs.

If one decides to create them, would such changes be accepted in the project? By closed issues it seems that you don't plan on accepting prs.

**Comment by jameskokoska** [comment]
Please read the README.
