### ISSUE TITLE
Sankey Diagram Chart or option to export into Sankey like data for 3rd Party Apps

### ISSUE THREAD

**Issue by dxloop** [jameskokoska/Cashew#204]
**Is your feature request related to a problem? Please describe.**
(This a very low prio feature request)
No, but would like to see the addition of a Sankey Diagramm, which is a more visually appealing diagramm for showing the expenditure flow

**Describe the solution you'd like**
Add a Sankey diagram feature to illustrate expense flow between categories or accounts for the current month or year.

**Describe alternatives you've considered**
Manually exporting data to third-party visualization tools or creating custom reports within Cashew.

**Comment by jameskokoska** [comment]
I definitely thought about this before. I find that since Cashew only sorts transactions into 2 main types (incoming/outgoing) the provided difference in the All Spending page is enough insight into this.

Closing issue for now as I find this diagram wouldn't provide enough insights considering its usability for most users.
