### ISSUE TITLE
[Feature Request] Auto transaction saving from SMS notifications of Bank Transactions while app is in background

### ISSUE THREAD

**Issue by Droyder7** [jameskokoska/Cashew#205]
**Is your feature request related to a problem? Please describe.**
I want to achieve Auto transaction saving from SMS notifications of Bank Transactions while the app is in background. 

There is already an Auto transaction feature in the app which parses the active notification and open up the add transaction page for adding it, but it only works while the app is in foreground and requires user input for saving the transaction. That isn't very useful because :
1. when the app is in background (which is most of the time), all the notifications which matches with Scanner Template is getting missed.
2. If it works also while in background, it will open up add transaction page from nowhere after parsing the notification, which seems abrupt in nature.

**Describe the solution you'd like**
The better way to do this can be as following:
1. Listen to incoming notifications even when the app is in background
2. Parses the notifications if it matches with Scanner Template and creates a transaction based on the details of the notification & other default params from Scanner Template. 
3.  Add the new transaction directly in the database & show a notification for the same newly added transaction to let user know about the new transaction that has been added
4. Tapping on the notification leads to you the add transaction page where the user can check or edit the transaction if required

In this way, we can achieve Auto transaction saving from SMS notifications of Bank Transactions while the app is in background. 

**Additional context**
This is a feature of many SMS based expense manager app which automates the tracking of transactions, which reduces the need of manually tracking the expenses & also increasing the accuracy of the spendings. This app also can benefit a lot if this feature can be incorporated.

NOTE TO THE CONTRIBUTORS
The Cashew app is a great app in itself, I couldn't found any other app which can fulfill most of my requirements to this extent & trust me I have tried dozens of them from closed source to open source. So kudos to the creators for making such a gem ✨

The only thing I missed in this app is this feature, so I thought may be this is the one that I have to compromise with here. But I was amazed, when I discovered it already has the base for building this feature which is `Auto Transactions`. It was enough motivation / excitement to get me started, so I tried some POCs for implementing this and made some progress. 

If I can complete this, I may raise a MR in the near future, but only if it's allowed in the first place, as I got to know contributions are not accepted currently. If that's the case, please be sure that I don't want any kind of compensation for the contribution, I just want to contribute to make this app awesome. That's it.

Thanks for sticking to the end. Do let me know what's your take on this.

**Comment by jameskokoska** [comment]
Thanks for the suggestion and offer to help!

Keep in mind debug features are not supported by Cashew. Because of this, I will close the issue. Feel free to continue the conversation however. Additionally, the Scanner Template implementation as it stands currently is a pretty confusing setup and very quickly hacked together. It isn't intuitive in its current form and will lead to more frustration rather than convenience. If this feature was to make production, it would require a usability rework. Since it's a debug feature, my time does not go towards improving or developing these features further.

However, that doesn't mean the debug feature can't support background reading of notifications as it stands. 

If you leave a PR it will most likely not make it into the main repo, however it can be of use to me in recommendations of how to implement this feature. I have looked into implementing reading notifications in the background very lightly, but it's not a straightforward task it seems. If you create a PR I can use it as a base and reference when implementing.

Want to reiterate, since it's a debug feature, my time does not go towards improving or developing these features further. So only if I find the time/inspiration I will actually decide to work on this (although I do think it will be an excellent addition and bring this feature closer to a production implementation)

An alternative you might want to consider is looking into App Links. App Links are fully supported by Cashew and allow for the automation of transaction creation to its fullest. Documentation can be found in the README.

Also, Google no longer wants apps listening to notifications. It is considered a security risk. This feature and its concerns were already addressed here: https://github.com/jameskokoska/Cashew/issues/42

**Comment by Droyder7** [comment]
Thanks @jameskokoska for your valuable feedback, this gives me more clarity about the Scanner Template implementation & the thought process that was behind building it, will surely keep it in mind.

You are correct, I also think Scanner Template implementation need some rework, as the current one is not so accurate and dependable for long-term use. So, I have changed the approach of scanning messages by using Regex for more accuracy & stability. 

In this approach I'm creating a regex pattern for each Scanner template, which can scan a message and parse the Amount & Title inside the message by using Named Capturing Groups in that regex pattern which stores the positional pattern of Amount & Title in it. 

I'm nearly done on the implementation part of this, will raise a PR shortly & Thanks again for considering my changes for future development of Cashew, really appreciate it.

And yes, I have also thought about using App Links for this feature, but there are two issues with that:
1. Have to run external script or application in background for scanning incoming notification and triggering the app link, which is not so great for long term use
2. Triggering the app link, opens the app in order to add transactions, which is not a preferable behavior for this feature. I want to add the transaction in the background & notify the user through just a notification.

**Comment by jameskokoska** [comment]
For an update on this issue, see https://github.com/jameskokoska/Cashew/pull/227#issuecomment-2960369814
