### ISSUE TITLE
Quick Actions not available on android 14

### ISSUE THREAD

**Issue by dagema1** [jameskokoska/Cashew#21]
First things first, I'd like to give a big thanks for the magnificent app you've given us.

I installed the app on two phones, one running Android 12 and the other running Android 14, and I noticed that the quick actions aren't available on Android 14.

**Comment by jameskokoska** [comment]
I can update the package to 1.0.6 but if that doesn't fix the problem you'll need to submit a bug report for the package here: https://pub.dev/packages/quick_actions/install

**Comment by dagema1** [comment]
I did some digging and here's what I found.

it looks like `runQuickActionsPayLoads()` isn't being called because `setDailyNotificationOnLaunch()` is throwing an error.

> Unhandled Exception: PlatformException(exact_alarms_not_permitted, Exact alarms are not permitted

This is because Android 14 introduced a new behavior: [Schedule exact alarms are denied by default](https://developer.android.com/about/versions/14/changes/schedule-exact-alarms)


So there are two solutions

1. add `<uses-permission android:name="android.permission.USE_EXACT_ALARM" />` which might require app store approval.
2.  add `<uses-permission android:name="android.permission.SCHEDULE_EXACT_ALARM" />` and request the permission on runtime.

**Comment by jameskokoska** [comment]
Thank you so much, I appreciate it! I'll look into it soon.

**Comment by dagema1** [comment]
No problem! I can confirm that adding the first permission did solve the problem on my emulator.

**Comment by jameskokoska** [comment]
Attempted fix in https://github.com/jameskokoska/Cashew/commit/0103dafab266a1f0ca3cab24f6f03c240327b1a5
More precisely here: https://github.com/jameskokoska/Cashew/commit/0103dafab266a1f0ca3cab24f6f03c240327b1a5#diff-b18594d63163e7005f53c6056aa3970f66cc334d12c7738ceb20b6bd0adaafaaR365

I opted to follow Google's guidelines, since it is not an alarm or calendar app, notification reminders do not need to be considered as precise (Can be off by a few minutes so the OS can be optimized)

If possible, could it be tested? I don't have access to Android 14 at the moment.

**Comment by dagema1** [comment]
I'll test it in a few hours and report back

**Comment by dagema1** [comment]
<img src="https://github.com/jameskokoska/Cashew/assets/13154918/79c7bc18-c4b8-4712-84b1-825279f880ab" alt="Screenshot_20231106-181854" height="300"/>

<br/>
<br/>

Yep, I can confirm that it's working.

**Comment by jameskokoska** [comment]
Thank you so much! Appreciate the help
