### ISSUE TITLE
[Feature Request] Default account adding transactions when filtering accounts

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#212]
**Is your feature request related to a problem? Please describe.**

Cashew has a default account named Bank. That means that every time a new transaction is added, the Bank is always selected by default as the account about to be added to the transaction.

When I filter the transactions of another account, the Cash account for example, on the transactions page and the search page; for several purposes, like reviewing transactions, editing transactions, and adding or removing transactions, of course only for Cash in the case of this filter.

The issue now is that I want to add transactions to the Cash, but by default, the transactions always select the Bank.

Because the filter is on the Cash, this means that now I actively want to work with the Cash account, and of course I also want to add transactions to Cash by default.

**Describe the solution you'd like**

Please add the function to automatically switch the default account by following the filter; as in the example above, automatically select the Cash account when adding transactions by following the Cash filter.

**Describe alternatives you've considered**

Please add the option to switch the default account when selecting the filter. This means that now, on the filter selection page, the ability to select a default account also acts as a filter.

**Comment by Abhijeet-AR** [comment]
This feature already exists. Go to accounts tab and select * to mark an account as primary.

**Comment by jameskokoska** [comment]
From what I understand the set filters should be followed when adding a transaction. I get that this use case makes sense in terms of 'the transaction added won't appear if the filters don't align' however, it's quite a complicated issue because for consistency it needs to be applied for all set filters. Unset filters though, will need to use their default. I find that if the app is just consistent based on the page the 'plus' button is pressed it makes the adding a transaction workflow more predictable, rather than inconsistent (because some filters may not always be set)
