### ISSUE TITLE
[Feature Request] Android widget enhancement 

### ISSUE THREAD

**Issue by tanhoaian01** [jameskokoska/Cashew#221]
**Is your feature request related to a problem? Please describe.**
Hello, I would like to ask for widget improvements. Right now the widget only shows account balance & total numbers of transactions. I would like to replace the total transactions with the relative date for my last expense (2 days ago, etc). It would act a reminder for me to not order more foods when I literally had them delivered 2 days ago.

I'd also want to report a UI bug. The + sign in the adding transaction button isn't centered in height. It's minor but when I place it along with other widgets, it stands out and draws unnecessary attention.

**Describe the solution you'd like**
1. Fix mis-aligned 'plus' icon in adding transaction button.
2. Add option to show relative date for last expense.

**Additional context**
![Screenshot_2024-04-11-13-32-45-944_com teslacoilsw launcher-edit](https://github.com/jameskokoska/Cashew/assets/133650669/98e0c25a-1e92-43b7-b143-83fdf3fd9315)

**Comment by jameskokoska** [comment]
I don't think it's necessary to show the user the last date of the entered transaction. Some days, users may not need to log down anything. Additionally, the daily transaction reminder notifications already serves the purpose of a reminder. However, I have taken the opportunity to center the plus button by using an icon instead of text. 

Improvements added here: https://github.com/jameskokoska/Cashew/commit/53e8fee1fa65c322238b3e46e4b47ac88512465a

**Comment by ngocanhtve** [comment]
> Additional context
> ￼

Excuse me! Which task app's widget is that?

**Comment by tanhoaian01** [comment]
It's Nova launcher and Smartspacer. The widgets are all from Google. The greetings and health stats are from Smartspacer's Health Connect plugin.

**Comment by ngocanhtve** [comment]
> The widgets are all from Google.

Which Google app? Please!

**Comment by tanhoaian01** [comment]
Google At a glance, Google Calendar and Google Keep.

**Comment by ngocanhtve** [comment]
> Google Calendar

Got it. Thank you!
