### ISSUE TITLE
[Bug] paid longterm lone Transactions Remain Visible in Transaction Templates

### ISSUE THREAD

**Issue by zeradawit** [jameskokoska/Cashew#260]
Issue Description: In the Cashew app, I’ve noticed that #paid and completed loan transactions are still visible in every transaction template, even after I’ve attempted to hide them in the long-term panel. Even the method of hiding them works, it’s overwhelming to manually hide these loan transactions every time. I have attached screenshot of the issue on the comment section.

The proposed solution to consider: 

Ideally, once a loan is settled and paid, it should remain hidden in the new transaction templet. Even there is no reason to show them as grayout text as the curent system dose.

**Comment by zeradawit** [comment]
![Screenshot_20240504_041020](https://github.com/jameskokoska/Cashew/assets/16444719/54300780-6590-4024-ab0e-43b2796aa59f)
![Screenshot_20240504_033713](https://github.com/jameskokoska/Cashew/assets/16444719/f48c8b3f-655f-43ee-8754-e440e4f2c830)

**Comment by jameskokoska** [comment]
This is the intended behaviour. Archiving/hiding something will always move it to the end of the list, however. This is because if you open a transaction that has an archived/hidden loan attached to it, the user wants to be able to see it selected and be able to edit accordingly without un-hiding/un-archiving.

**Comment by Michael152843** [comment]
>This is because if you open a transaction that has an archived/hidden loan attached to it, the user wants to be able to see it selected and be able to edit accordingly without un-hiding/un-archiving.

@jameskokoska wouldn't it be a better approach to temporary display a greyed out chip with the archived/hidden loan, goal, budget or account connected to a transaction that is open? 

That way we would have a clearer `Add Transaction` page for new transactions, free of unwanted loans, accounts etc., but at the same time if some old transaction is open, a user could still access an archived/hidden loan, account, etc. that is connected to it.

**Comment by imericxu** [comment]
@jameskokoska The concern of manually hiding loans being tedious wasn’t addressed. It would be much easier if there was a visibility toggle on the edit page of loans, so you don’t have to go into the manage loans list, find the loan, and then toggle it.

Otherwise, another simple solution, would be to insert new loans to the top of the list instead of at the bottom (where you’d expect the hidden loans to be). To add on to that, the list management page could be like a todo list, where you “check off” loans, which then go to the completed section, sorted by descending interaction time. Here’s a mockup:

<img src="https://github.com/user-attachments/assets/19413a67-fbfd-4f34-8971-5c5e4338b66b" alt="Redesign" width="500" />

**Comment by jameskokoska** [comment]
> The concern of manually hiding loans being tedious wasn’t addressed. It would be much easier if there was a visibility toggle on the edit page of loans, so you don’t have to go into the manage loans list, find the loan, and then toggle it.

That has already been addressed here https://github.com/jameskokoska/Cashew/issues/199. Please search past issues first. 

> To add on to that, the list management page could be like a todo list, where you “check off” loans, which then go to the completed section, sorted by descending interaction time. 

This is an interesting idea. However, the way the ordering is tracked in the database doesn’t allow for separate sections unfortunately. Additionally, when a loan is archived, if it disappears into another section below it creates a confusing user experience. The user may think it was deleted.

**Comment by Michael152843** [comment]
There is another issue related to the lack of a better hide/archive functionality for loans: since one time loans don't allow to track repayments to a different account, the user is forced to use long term loans in such cases. This leads to a huge number of loans cluttering the Transaction page once the app has been used long enough. The same issue exists for accounts, budgets & goals.

I think it's important to keep in mind that in such apps the users' data can only grow, so the ability to completely hide/archive certain elements is essential.

**Comment by jameskokoska** [comment]
The way archiving is handled has been updated in the beta (release TBD) and is hidden in the UI. It better matches the discussion of this issue. 

![image](https://github.com/user-attachments/assets/4e8920aa-42bd-4cc2-9f85-2ebe2e6bfce6)
![image](https://github.com/user-attachments/assets/2de9c537-2118-493e-a0d1-63cbf8be6a23)

**Comment by jameskokoska** [comment]
This has been added in the beta. Archiving has been improved, with a separate archive section and archived items are no longer listed when creating new transactions. 

See #725 for Beta Testing instructions and information
