### ISSUE TITLE
[Feature Request] The upgrade to Cashew Pro button does not allow selection of Google account.

### ISSUE THREAD

**Issue by TJMac93** [jameskokoska/Cashew#278]
**Problem**
When selecting the upgrade for Cashew Pro, one Google account is selected by default and there is no way yo change it. Strangley I have three Google accounts. I use one for play store, I use a separate one for Cashew drive backups, and it selects the third by default.

**Solution**
The same google sign in page that appears on backup selection should appear for the purchase flow.

**Comment by ngocanhtve** [comment]
There is a much simpler solution: select the account you want to pay for in Google Play first.

**Comment by ngocanhtve** [comment]
It must work because I've done it before.

I set up payment method for account 1, for example. Log in to Cashew with account 2. Now I make payment from within Cashew, payment will be completed using account 1 previously set up in Google Play.

And it doesn't matter which account you log into Cashew with, as long as Cashew is installed on a device with account 1 logged in in Google Play, Cashew Pro is always ACTIVATED.

This means that at this point, you only need a valid payment method set up for the account you want to choose to pay.

**Comment by ngocanhtve** [comment]
I suggest you the last method if the above comment still doesn't work for you.

If you choose account 1 to pay. Sign out of all other accounts. Log in to Cashew by account 1 to make payment and of course payment will be completed using account 1, because it is the only payment account on the device.

Then log back into the Google account you want Cashew to back up data to. At this time, Cashew Pro is still valid, but your data can still be backed up to the account you desire.

You may want to back up your data to an SQLite file in case something goes wrong when switching between Google accounts. After got Cashew Pro and logging back into the account you desire. You can import previously exported SQLite files.

**Comment by jameskokoska** [comment]
Unfortunately I don't think the IAP library (https://pub.dev/packages/in_app_purchase) supports an account selection. You can raise an issue on that repository.

Seems like the suggested solution by @ngocanhtve is the way to go. Thanks for helping out!

**Comment by TJMac93** [comment]
Unfortunately this issue still hasn't really worked. I did as @ngocanhtve suggested.
I
1.  signed out of all google accounts except the one I use for play store
2. Purchased Cashew Pro (This did work)
3. Signed back in to my Google accounts
4. Cashew no longer recognises that I have pro. Restore Purchases does not work

I also exported my cashew data, and now use my play store google account for Cashew backups and it still does not work. The app is insisting that I use one of the other google accounts for purchase. Signing in to `tom...@gmail` on my device at all is causing the app to see only that account. 

> And it doesn't matter which account you log into Cashew with, as long as Cashew is installed on a device with account 1 logged in in Google Play, Cashew Pro is always ACTIVATED.

The probem seems to be that Cashew has no idea that the account that has Cashew Pro exists.

Should I reraise this issue as a bug rather than a suggestion?

**Comment by TJMac93** [comment]
To try be clear.

- I use `acc_one@gmail.com` for Play Store. This is the only account I have ever used on the play store. I can see a receipt for Cashew pro in the play store on this account.
- I (now) use `acc_one@gmail.com` for Cashew backups.
- When I click on the Cashew Pro button, it asks me to buy it rather than showing I have it. If I click restore purchases, it flashes on screen that purchases were restored. If I choose an option from Lifetime, Yearly, or Monthly, it asks me to add a payment method to `acc_two@gmail.com`

**Comment by ngocanhtve** [comment]
It's very very strange that it doesn't work on your device but works on mine. Technically I don't know how Cashew works, I'm just sharing my actual usage experience like that. 😑

**Comment by TJMac93** [comment]
Thanks, I appreciate you trying to help!

**Comment by TJMac93** [comment]
I think I discovered the issue with this. The same thing has happened where google maps forgot my settings and gave me introductory popups long after I'd already agreed with them.

@ngocanhtve suggested choosing the correct account in google play before attempting to purchase and that did not work. But what fixed the maps issue (and I expect its the same for cashew) is to change the account in the Google Search app. Even if the account is marked as default, if you have changed which account is selected in the search app it seems to proliferate across the device. The play store shows `acc_one@gmail` and the search app shows `acc_two@gmail`, then `acc_two` is the one that will be used.
