### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by Mark4256** [jameskokoska/Cashew#279]
**Description**
Automatic sync is not working recently and showing error as "connection reset by peer". Since 20th May there was no backup created by app. Kindly check and help to resolve the issue. (Screenshot attached from backup page)

**Details**
 - Device: Samsung Galaxy A53 5G
 - App Version: v5.2.9+363, db-v46

**Screenshot**
![Screenshot_20240524_203518](https://github.com/jameskokoska/Cashew/assets/149863997/9d3547cd-d5e6-478e-9c47-17bd7bb01455)

**Additional notes**
Thanks for this incredible app. Love it

**Comment by jameskokoska** [comment]
Thanks for reporting this issue! It seems it is an issue with your connection to the Google Drive servers. Please consider restarting the application to re-initialize the connection or check your Wi-Fi connection/permissions to access Google's servers. Unfortunately, there's not much I can do on my part since the API key is still functional. 

Another thing that could be worth checking is to ensure Cashew has proper permissions to access your Google Drive.

Closing issue for now as unable to replicate.
