### ISSUE TITLE
[Question] Why isn't the 5.3.1 release on the github releases page yet?

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#294]
**Describe your question**
Build 5.3.1 was released on Google Play 3 days ago, before that was v5.3.0. Why are both of these build not released on the github releases page?

**Comment by jameskokoska** [comment]
Releases will be available when they are ready.

**Comment by HappyBear-btc** [comment]
> on the github releases page?

you can see 5.3.1 if you click on "Tags" to the right of the releases...

**Comment by HappyBear-btc** [comment]
> Can show me an apk on that tag

I guess apks are available on release only... tags don't have it.

**Comment by ngocanhtve** [comment]
> I guess apks are available on release only... tags don't have it.

Did you actually read my question above to understand the situation? 

Usually releases come with an apk, what's interesting is that 5.3.1 has been released on Google Play but not on github, that's is question. 

And precisely because the tag 5.3.1 has been released on github without the apk is what I'm wondering about.

**Comment by jameskokoska** [comment]
Just because the tag is there does not mean the release is ready. I have tagged it and have a draft release on GitHub but I did not finalize the features for 5.3.1 (since there are versions past that, e.g. 5.3.1+379, 5.3.1+380 etc still in development) as requests/bug fixes keep rolling in. Once these have settled down and the app is tested, it will be ready for release.

**Comment by ngocanhtve** [comment]
I already got it. It's just that he told me about the tag so I answered him.
