### ISSUE TITLE
[Feature Request] Allow purchasing PRO without Google Services

### ISSUE THREAD

**Issue by prkuctd** [jameskokoska/Cashew#295]
**Is your feature request related to a problem? Please describe.**
Folks who do not use Google Services, either for privacy reasons or being forced by manufacturer, are unable to purchase Cashew Pro. They are limited to the free version, and have no way of upgrading.

**Describe the solution you'd like**
Implement alternative licences, independent of Google Play. For example, MyExpenses allows me to purchase the licence through Google Play and PayPal. If you pay with PayPal, you will receive a licence code that you can expand your licence within the app.

**Describe alternatives you've considered**
Ivy wallet, MyExpenses

**More context**
This is pretty important feature and should be implemented. Not only Cashew Team is losing money, but also the lack of the alternative Is frustrating for the users.

Thank you for being there, you're doing an amazing work. Cashew is great, and this is the only feature that keeps me from using it.

**Alternative solution**
If, for some reason, you decide against implementing alternatives for Google Play purchases, please provide GitHub .APK file with PRO version free of charge, and add a CTA button to donate. There is no reason to limit open source loving folks with features while they're unable to upgrade by any method.

**Comment by HappyBear-btc** [comment]
I would also add that buying a license as a gift to someone else is something I would consider.
just FYI @prkuctd AFAIK there're no features that are blocked from the free version, you can open the Pro features after some prompt...

**Comment by jameskokoska** [comment]
Cashew's license check uses Play Services as verification. Cashew does not store any users information/login on any servers, so a license check without a Google account is not possible.

Additionally, as @HappyBear-btc mentioned there is no limitation of features in the free version. Because of this there are no plans to support alternative billing methods/a unrestricted APK. 

As an aside; Cashew relies heavily on Google Services for many features such as cloud backups and syncing. A version without Play Services would deviate from the current feature set.
