### ISSUE TITLE
[Feature Request] Ability to add attachments to transactions from share menu (of other apps)

### ISSUE THREAD

**Issue by Akv2021** [jameskokoska/Cashew#317]
**Is your feature request related to a problem? Please describe.**
When we've made a payment on any banking application, it gives an option to share receipt (image) after payment is done. The share menu lists apps to which the screenshot of payment can be uploaded. Currently the share menu does not list Cashew app.

**Describe the solution you'd like**
Cashew should be present in the list of applications in share menu. From there the user can directly create a new transaction with the attachment (or you can also provide feature to add attachment to any existing transaction).

**Describe alternatives you've considered**
Right now, the only option is to save the image to Gallery. Close Payment application. Open Cashew. Select or create new transaction. Add attachment. Select image from Gallery. 

This can also be extended to enable attaching files since files can also be attachments in Cashew transactions.

**Comment by jameskokoska** [comment]
I think the workflow that makes the most sense is to add an attachment when creating the transaction itself. Cashew is different than say a cloud file system app or an email. There are other options when adding an attachment as well such as immediately capturing a picture. Additionally, since Cashew isn't a native application, adding a native share implementation given this workflow is not something that would be worth an investigation at this time.
