### ISSUE TITLE
[Feature Request] Pay Check Splitter

### ISSUE THREAD

**Issue by jacobgonzales20** [jameskokoska/Cashew#322]
**Is your feature request related to a problem? Please describe.**
Unable to split paychecks to promote saving

**Describe the solution you'd like**
A paycheck splitter calculator for saving strategies like 20/30/50 

**Describe alternatives you've considered**
excel spreadsheets, works great. It's just a hassle

**Comment by jameskokoska** [comment]
Cashew is optimized so that you can quickly add multiple transactions. Cashew is also optimized so that it is easy to use while offering the flexibility for everyone to track their finances in their own way. 

I recommend creating separate transactions for how you would like to split it up. There is an included calculator for your convenience.
