### ISSUE TITLE
[Feature Request] Make budgets updatable without losing past history

### ISSUE THREAD

**Issue by dymester** [jameskokoska/Cashew#335]
**Is your feature request related to a problem? Please describe.**
I want to be able to have a budget, that adapt along my usage of the app. For example, one year ago I had some financial responsibilities that I no longer have, and an "different" allowance that I could spend, but, if I change my budget it retroactively updates all previous months, hiding the fact that certain month I failed my quotas.

**Describe the solution you'd like**
The solution I would like could be two fold:

1. Make it possible do "update" a budget, this would change the budget values but keep the budget intact for past timeframes (whatever timeframe the budget follows);
2. As an extra, allow to define future timeframes up-front, so for example, I have a monthly budget, so if I want to prepare a budget 3 months from now, I would just go to a selector, and let me setup the update described on point 1. This update could apply to all future instances or just that specific timeframe (I think that just the timeframe gives more control, but I would like to see your opinion);

**Describe alternatives you've considered**
Right now I just lose my historical data on this one, while inside of the app. I track my budget's history on an Excel right now. 

**Additional context**
This capability is based on [Money Manager](https://realbyteapps.com/) the app I have used for a few years before finding Cashew, on this app you have the ability to setup a "Default Budget" that applies to every timeframe, but you can also override that budget for specific timeframes, whenever in the future they may be. This give a lot of options to start planning out expenses.

I believe I have not seen this issue anywhere so if it is a dup. I am sorry.

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating feature requests. Duplicates will not be addressed again.**
Not all feature requests will be considered. This budget app was created with careful thought given to each feature's usability and prevention of feature overload. As you use the app, you will discover possibly related useful features and that may not be obvious right away. 
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment]
Edit: See the FAQ: https://cashewapp.web.app/faq.html#budget-period-amounts

___

Currently the way the app functions, the limit will be applied to all past cycles of a budget. This was an intentional design decision to make it easy for people to create a budget that can be used across multiple past periods and to encourage stable spending habits. I understand that the history may be confusing as you change your limit (and it will show a different goal). This budget app has many design decisions making it easy for all users while being able to support complex use cases. 

If you have a dynamic limit I recommend creating a custom budget for each period with a respective limit. (See https://cashewapp.web.app/faq.html#budget-cycle) This will give you full control over the time limit of each budget you create along with the amount limit. As you create budgets, you can also archive them to not appear in your list, so no worries about creating too many budgets.

**Comment by anjuthanmj** [comment]
@jameskokoska I feel that this request makes more sense than the existing feature. As years goes by, people would change the budget goals. I do not think many people want to get the past budget goals get edited as for the past month their goal was different.

**Comment by j-perezr** [comment]
Absolutely, this is the main paint point for me for this app compared to other like 1money, as I lost my budget history and it is not feasible having tons of budgets for the same thing but for different periods.

**Comment by fravel77** [comment]
I bought the Lifetime license and for the first time since I use this kind of app I spent quite an effort of time to import transactions from past year. This preamble just to make you understand I personally consider this app as one with a very high potential.

What proposed from the submitter makes totally sense. This kind of app are supposed to be used across years and in a so wide time span things changes in term of what you need but also what you can afford.
For instance, you start as a couple without children but then you have on child and then another ones. I have to adapt accordingly and realistically my grocery budgets, Holiday budgets (not anymore 2 flight tickets but 4), etc etc.
Or, compared to 3 years ago, I do now a Job that gives me much more money so I can allow my self things that before i was not considering to buy. Hence I can increase my "leisure" budget".

But at the same time I want to keep track about my capacity to stick with the budget each year I setup. I want to have track on how "good" or "bad" I was staying below the budget I setup.

Complex doesn't mean Hard or Difficult but very often means more complete. :)
