### ISSUE TITLE
[Feature Request] Ability to archive categories/subcategories

### ISSUE THREAD

**Issue by Akv2021** [jameskokoska/Cashew#336]
**Is your feature request related to a problem? Please describe.**
Categories/subcategories lack the option to archive unlike goals/Budget

**Describe the solution you'd like**
Archive option which enables to reuse the categories in future. Currently there's only option to delete the categories.

**Describe alternatives you've considered**
Deleting and recreating the categories when required in future.

**Additional context**

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating feature requests. Duplicates will not be addressed again.**
Not all feature requests will be considered. This budget app was created with careful thought given to each feature's usability and prevention of feature overload. As you use the app, you will discover possibly related useful features and that may not be obvious right away. 
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment]
There are no plans to allow archiving of categories. Categories should be used throughout the lifetime of the application, especially since each transaction requires a category and it's difficult to determine usability when showing spending statistics with archived categories.

**Comment by Akarumey91** [comment]
Hi @jameskokoska !
I want to ask about a solution for my problem related to this topic.
In my previous app, I created a few categories to track some expenses (for example, Business Trip, Renovation). These expenses were for a short period, so I archived them to prevent them from appearing in the dropdown and to keep the UI clean.
In this app, I can’t do the same. When I transfer my data, these categories reappear, and I don’t want to delete them because I would lose my records.
What can be done in this case?

**Comment by jameskokoska** [comment]
This has been added in the beta. Categories can now be archived. They are hidden from the category selection UI. Archiving a category will not hide related transactions and therefore not affect existing statistics - which is the intended behaviour behind archiving. Archiving functionality was also added to accounts in the beta.
If this is still an active issue, add an update and this ticket can be further discussed and reopened as necessary. See #725 for Beta Testing instructions and information.
