### ISSUE TITLE
[Bug] Quick Transactions Pressing Enter On Keyboard Interaction

### ISSUE THREAD

**Issue by Radwan-Albahrani** [jameskokoska/Cashew#379]
**Describe the bug**
In the other menus (for example adding a transaction) pressing Done on the keyboard takes you to the next step. However in the quick transactions page, pressing Done only dismisses the keyboard

**How to reproduce**
- Hold the + button
- Select "Transfer Balance"
- Click on Edit button
- Add a title
- Click Done on the keyboard

Expected Behavior:
The keyboard would dismiss and go back to the amount selection popup. The details page would dismiss with the keyboard

Actual Behavior:
The details page does not dismiss with the keyboard.

**Details**
 - Device: iPhone 14 pro
 - App Version: 5.3.8-410

**Comment by jameskokoska** [comment]
Because there are other options to configure, submitting the text field should not close out of this interface. The button on screen should be the primary UI element to continue the workflow, which is what is currently implemented ("Set Details")

Another example of this is when adding a 'Title', submitting the entry for the title name will not add the title because of the category selection.
