### ISSUE TITLE
[Question] - Version mismatch

### ISSUE THREAD

**Issue by gauravagarwal2704** [jameskokoska/Cashew#396]
**Describe your question**
“I noticed that the app version on Google Play Store is 5.4.0, but the version available on GitHub at [here](https://github.com/jameskokoska/Cashew/blob/main/budget/pubspec.yaml#L18) is still ⁠`5.3.9+411`.

Can you clarify why the Play Store version has been updated, but the main branch on GitHub hasn’t? Is there something I’m overlooking?

Thanks.

<img width="718" alt="image" src="https://github.com/user-attachments/assets/1e93d40e-fdca-4cf1-becb-4a3ae88dfe2e">

**Comment by jameskokoska** [comment]
My local branch hasn't yet been rebased and pushed fully into the main branch here. I haven't had much time and the GitHub release isn't ready yet. Once bug fixes die down and I get the chance, I will rebase and release when I have the time.

**Comment by PitiBouchon** [comment]
I'm wondering (because I don't know) why is it **not** annoying to update on playstore while it is for github ?

**Comment by acmpo6ou** [comment]
This looks pretty shady, it's like the app's source code is intentionally not being released to GitHub, so that people install the Play Store app, for which we can't see the source code.

It's like the app started out open source, and now it's continuing closed source. The last update on Google Play says "Jun 4, 2025", while the freshest commit here on GitHub is from 9 months ago.

**Comment by PitiBouchon** [comment]
I don't know why this issue is closed, the last github release is more than a year old while the play store version has many new features (and not only small bugfixes)

A CI job can publish a new github release, I don't understand why would it be harder to release on github than on the play store.

**Comment by gauravagarwal2704** [comment]
Hey @jameskokoska, it’s been a while since the main branch has changed. Just wondering if there’s any chance of reopening this or pushing some updates soon? Would love to see the project stay active and keep improving. Thanks!

**Comment by jameskokoska** [comment]
The current state of development is addressed in this thread: https://github.com/jameskokoska/Cashew/issues/725

**Comment by PitiBouchon** [comment]
I think open-source apps often do the opposite : push release candidate on github and when a version is good enough, release a new version on both github and play store.
And that's why the way cashew does it (by testing on play store and releasing when a version is fully complete on github) is kind of strange.
