### ISSUE TITLE
[Bug] WebApp freezing

### ISSUE THREAD

**Issue by Shadorain** [jameskokoska/Cashew#408]
**Describe the bug**
The webapp version freezes after some time (untested on Chromium). I turned off any idle tab sleeping but it still freezes after some time. The time doesn't seem to change for me unless I refresh and keep it open and am actively using the tab.

This is mostly frustrating because of the issue with the webapp version unable to keep the Google login session. Would this be a problem if I self hosted a cashew instance?

**How to reproduce**
Open a Cashew webapp tab and then go off and do something for some time and try to come back to it without refreshing. The time will be behind and might be flickering and try to click on any elements in the page.... They will be stuck. Refresh and it should be back to normal.

**Screenshots/videos**
Flickering video after it froze:
https://github.com/user-attachments/assets/64eb12ae-1d55-490c-895d-b85f95321a9c

**Details**
 - Device: Arch Linux Desktop (Hyprland Wayland)
 - App Version: Latest (WebApp)
 - Browser: Firefox

**Additional notes**
I notice too the time might flicker between a next minute after its frozen.

**Comment by jameskokoska** [comment]
Unfortunately it seems that this issue is either related to the browser or host device. Usually when tabs are inactive they enter a sleep mode to save resources. 

The Flutter engine performs best in Chrome and if you are able to provide any screenshots or videos replicating the issue in Chrome, I recommend reporting the issue to the Flutter repository if it seems outside the scope of the Cashew app.

Closing issue for now as it seems like an issue with host.

**Comment by Shadorain** [comment]
I figured it had to do with that yeah. Wanted to make sure though. Will try with Chromium and report back!
Thank you!
