### ISSUE TITLE
[Request] Create transaction from Notification

### ISSUE THREAD

**Issue by fmaar** [jameskokoska/Cashew#42]
Hi, I've been using Bluecoins for years and I want to migrate to Cashew (BC's iOS support is not the best). One feature that I'm going to miss is the ability to create a transaction out of a push notification. 

How the feature works on Bluecoins:
1. When the feature is enabled, you can configure if you want to catch SMSs notifications only, or any other app's.
2. When a notification for any of these application comes, Bluecoins creates another push notification that when clicked, launches a popup that lets you configure the transaction's information.
3. The "amount" field is prefilled with the notification content's numeric values (inside a Selector)
4. You can also configure the transaction's name, account, etc.

I'm just wondering if this could be consider in the future, doesn't really matter how long it takes; or if there's a limitation on the framework that doesn't allow this.

If this question has already been asked before, please feel free to close/delete this issue.

Best regards.

**Comment by jameskokoska** [comment]
I would really say there's a limitation imposed, however there are some security concerns with apps requesting this types of permission access nowadays. Currently no plans to implement the feature because of this 

See this article: https://support.google.com/googleplay/android-developer/answer/10208820?hl=en
