### ISSUE TITLE
Problems with the Date Range Picker

### ISSUE THREAD

**Issue by Michael152843** [jameskokoska/Cashew#426]
**Describe the bug**
Currently there is no way to type the dates using the Date Range Picker since its format requires slashes, and this symbol is not included on the number pad that pops up.

Also, the Date Range screen itself seems to have some kind of a button that doesn't do anything partially visible at the bottom.

Besides that, the Save button on this screen is barely visible and doesn't correspond with the overall UI of the app.

**How to reproduce**
Transactions page > Search > Select Range

**Screenshots/videos**
![Screenshot_20240916_214044](https://github.com/user-attachments/assets/2e62a5da-e8d3-4426-b30c-f7fc6eec91f5)
![Screenshot_20240916_214118](https://github.com/user-attachments/assets/907e9acc-514e-437a-a7a9-d6187ea04bae)

**Details**
 - Device: Android
 - App Version: 5.4.1+414

**Comment by jameskokoska** [comment]
It seems like your system keyboard doesn't support input of "/" in the number keyboard. The official Android keyboard GBoard however does. This seems like an issue with Flutter itself, you can create an issue to address that there. Additionally, the Save button is also implemented by Flutter.

The extra button at the bottom is the "All Time" button. However, it's implementation to the popup was never the best.

The select date range has been revamped here: https://github.com/jameskokoska/Cashew/commit/66470032e6879b026f6c66345147115df80e91de and doesn't rely on the text input provided by Flutter by default. The Save buttons theme has been configured to make it stand-out more in the UI (since the other UI is not used, the TextButtonTheme can be altered without affecting the other input - Flutter default, as it is not longer used)
