### ISSUE TITLE
[Request] iCloud support

### ISSUE THREAD

**Issue by fmaar** [jameskokoska/Cashew#43]
Hi,

I'm wondering if there are plans to support iCloud accounts. I have no problem using GDrive, but sure would like to have everything on the same account.

Best regards.

**Comment by jameskokoska** [comment]
No plans to support iCloud. Since the app doesn't rely on account creation (just used for backups) the limit imposed by Apple to allow Apple login and iCloud support is not enforced on this app. The iOS app is also not a priority in specialized features as Cashew for iOS is running at a loss in profits as of now.
