### ISSUE TITLE
[Feature Request] Option for Cent-Based Amount Entry

### ISSUE THREAD

**Issue by nazmi** [jameskokoska/Cashew#440]
**Is your feature request related to a problem? Please describe.**

Hello developer, this is QOL request.

Entering amounts with cents requires clicking the decimal point, which can be inefficient.

Benefits:
Faster entry for amounts with cents (more common)
No need to input decimal point

Caveat:
Requires two extra zeroes for whole dollar amounts.

**Describe the solution you'd like**

Add a toggle option to switch the default input unit between dollars and cents.

**Comment by jameskokoska** [comment]
I've thought about this, and because the `SelectAmount` is already quite complex in the way it functions to ensure usability (i.e. disable buttons to ensure decimal precision to that of the account etc) and because it is designed as a calculator - it doesn't make much sense from a usability standpoint to have this type of amount entry. In the end, it's a calculator input and should function in a familiar way to other calculators.
