### ISSUE TITLE
[Feature Request] Savings Budget Breakdown Period

### ISSUE THREAD

**Issue by Anu6is** [jameskokoska/Cashew#465]
### Is your feature request related to a problem? Please describe.
When setting up a savings budget, the current system displays a daily breakdown of how much you need to save to reach your goal. For longer-term budgets (spanning more than a month), it might be helpful to display savings targets on a weekly or monthly basis instead of daily.

Example: If you're creating a 1-year savings budget for home insurance, the current message would be: “You should save $10/day for 364 more days.” A more useful suggestion might be: “You should save $300/month for 12 more months.”

### Describe the solution you'd like
I would like an option to choose the interval for the savings breakdown—whether by Years, Months, Weeks, or Days.

### Describe alternatives you've considered
None

**Comment by jameskokoska** [comment]
Hi there! Thanks for the suggestion. I have thought about this before and it can be useful for goals too. However, I think that because each transaction is per day, it might be difficult for a user to grasp what it means to for example "save 300$ per month" when it's over a very large term. It's difficult for users to understand how "on track" they are. To keep it straightforward to the user, per day averages make the most sense intuitively for projections. Additionally, the period will keep adjusting when the end date approaches - for example it will be per month at the beginning, but when there is less than one month remaining, what does the projection look like?

**Comment by venusddev** [comment]
I believe for the audience that does use expense trackers and budget apps like this, it's a really convenient feature, it'll 100% not cause any confusions, at worst some people will just not use it.

Especially things like when you have leftover in the budget, you could add an option to let it build up into next month's budget

**Comment by venusddev** [comment]
It's such a key feature that I'm willing to add it myself although it'll take time due to me not knowing how to use Flutter or Dart as I've never used either of those as of today.

Though for that I'll need to know beforehand if you would accept a PR adding that or is forking going to be the only way to add the feature to the app(with credit of course)
