### ISSUE TITLE
[Feature Request]  Implement Multiple Filter for Notes

### ISSUE THREAD

**Issue by MohammadShabib** [jameskokoska/Cashew#467]
In your filter functionality, you can filter using different titles, but the same option is not available for Notes. It would be a valuable feature if you could implement similar functionality for filtering Notes as well.

**Comment by jameskokoska** [comment]
Because notes can contain multiple lines of extra information, from a workflow perspective this isn't an intuitive use case. A comma separated multiple title filter however is intuitive since titles are limited to one line/entry.

**Comment by jameskokoska** [comment]
Edit: After some thought I *may* plan on implementing this feature, however I will need to think more about the use case and implementation user experience.

**Comment by Michael152843** [comment]
@jameskokoska

A possible implementation of this functionality would be to allow a comma separated multiple filter by keywords within notes, rather than by their whole content. The keywords, ideally with autocomplete functionality, might start with `#` like hashtags, or with `@` like Google smart chips (or both like here on GitHub).

This way if a user has transactions with the following notes :
`• #groceries from Tesco`
`• Amazon #delivery`

... than both of them could be filtered by typing `#groceries, #delivery`
