### ISSUE TITLE
[Feature Request] Option to Automatically Adjust Scheduled Transactions for Weekends

### ISSUE THREAD

**Issue by AnyByte** [jameskokoska/Cashew#474]
**Is your feature request related to a problem? Please describe.**

I receive my salary on the 5th and 20th of each month. However, when these dates fall on a weekend, my salary is deposited on the previous weekday. Currently, Cashew does not allow for scheduled transactions to automatically adjust when the due date lands on a weekend, which creates inaccuracies in tracking income or expenses. It would be helpful to have an option to handle such cases automatically.

**Describe the solution you'd like**

I'd like to see a feature that allows users to set rules for scheduled transactions when the due date falls on a weekend. The options could include:

* Move to the next weekday
* Move to the previous weekday
* Move to the nearest weekday
* Skip the transaction

This would help ensure scheduled transactions match real-life scenarios more closely, such as receiving salary payments.

**Describe alternatives you've considered**

Manually adjusting the transaction date every time it falls on a weekend is one alternative, but it is cumbersome and error-prone, especially for recurring transactions like salary or bills.

**Additional context**

Many users may have similar needs for automatic adjustments of transactions when weekends or holidays interfere with their normal payment or expense schedules. Implementing this feature would save time and improve the accuracy of financial records.

**Comment by jameskokoska** [comment]
The way Cashew supports upcoming payments it support this use case already. When you actually “Collect” or “Pay” an upcoming transaction it will get added on the current date at the current time. Therefore, even though it is scheduled for the 20th or the 5th, when it is marked as paid that date will be accurate since it will be marked on the day it actually occurred - changing the date and time of the transaction to the current. Supporting different cases such as a Payment or Skip next weekend or next weekday creates a complex inconsistent user experience. Instead Cashew’s implementation of “Marking things when Paid or Collected” to the current date fixes this issue of when the payment or collection actually occurs.
