### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by drshtmstry** [jameskokoska/Cashew#475]
**Feature request**

1. Add option to count balance correction transaction as expense (per transaction entry, not for all transactions).
2. Transfer can also be separated as new  transaction category instead of merging with Balance correction.
3. Separate Income/Expense tabs for categories.
4. Show more matching titles when entering transaction. Currently it only shows 1 title even if there are multiple matches available in titles.
5. Show only Income categories & sub categories (& also titles) when adding Income transaction. (& vice-versa for Expense)
6. Auto add Titles should follow category & subcategory. (It is creating same Title under Main category and also under Sub category).
7. Option to replace Budgets in bottom bar with Accounts or Categories.
8. Indian currency format comma separator (Rs. 1,00,00,000.00). I have system language & region setting to India but it is not followed by app. **[Never mind it is RealmeUI bug, Eng India setting is showing £ as currency]**
9. More common icons for categories. (I know we can use emojis, but native icons look better).

**Comment by Michael152843** [comment]
For 1 and 2 you can simply create new categories if for some reason you want Balance Corrections and Transfers to be treated as expense/income (though they shoundn't be)

And for 5 you can already do that for categories - just press the three dots when selecting a category and there you can choose to display only expense/income categories.

Also, just to let James know, it is incredibly convenient that Cashew treats categories as both income and expense - this way one can have two times less categories compared to other apps. It was a selling point for me

**Comment by Michael152843** [comment]
> I don't want transfer as income/expense. (This app does that by default)

Transfers do not contribute to total income/expense though

> When I add a transaction, by default it is expense and it shows both type of categories

I think this is because the app has no way of predicting what type of transaction you are about to input, so first it provides you with all of the categories at once, which makes perfect sense.

I barely use titles though, so can't comment on those

**Comment by drshtmstry** [comment]
> > I don't want transfer as income/expense. (This app does that by default)
> 
> Transfers do not contribute to total income/expense though
> 
> > When I add a transaction, by default it is expense and it shows both type of categories
> 
> I think this is because the app has no way of predicting what type of transaction you are about to input, so first it provides you with all of the categories at once, which makes perfect sense.
> 
> I barely use titles though, so can't comment on those

Example of Balance correction which counts toward expense.
![IMG_20241020_200318](https://github.com/user-attachments/assets/b676f94f-38b1-4b68-bac2-aeff9c28e6a9)

Example of transfer (which is not a category like "Balance correction") but a separate type of transaction.
![IMG_20241020_200215](https://github.com/user-attachments/assets/3748331d-ae66-4df2-9118-8493187b2c23)

**Comment by jameskokoska** [comment]
Thanks for helping answer some questions @Michael152843 

> 1. Add option to count balance correction transaction as expense (per transaction entry, not for all transactions).
> 2. Transfer can also be separated as new  transaction category instead of merging with Balance correction.

As mentioned by @Michael152843:
You can simply create new categories if you want Balance Corrections and Transfers to be treated as expense/income

> 3. Separate Income/Expense tabs for categories.
> 5. Show only Income categories & sub categories (& also titles) when adding Income transaction. (& vice-versa for Expense)

You can tap expense or income at the top when first selecting to only show those types of categories. You can select it again to deselect it and show the default (both expense and income)

> 4. Show more matching titles when entering transaction. Currently it only shows 1 title even if there are multiple matches available in titles.

Duplicate and already acknowledged in https://github.com/jameskokoska/Cashew/issues/38. Please check past issues to ensure you are not duplicating feature requests.

> 6. Auto add Titles should follow category & subcategory. (It is creating same Title under Main category and also under Sub category).

Duplicate and already acknowledged in https://github.com/jameskokoska/Cashew/issues/392. Please check past issues to ensure you are not duplicating feature requests.

> 7. Option to replace Budgets in bottom bar with Accounts or Categories.

You can already change the tab shortcuts by long pressing and selecting the page of your choice.

> 8. Indian currency format comma separator (Rs. 1,00,00,000.00). I have system language & region setting to India but it is not followed by app. **[Never mind it is RealmeUI bug, Eng India setting is showing £ as currency]**

Since the app uses the devices locale and it is not being properly detected you can create an issue on the Flutter repo.

> 9. More common icons for categories. (I know we can use emojis, but native icons look better).

I'm not sure what you mean by "native icons". Cashew already includes many icons to choose from and more can be recommended inside the app and they will be added if there is a gap that needs to be filled.


It seems that referring to another app when asking for these features. Cashew is not trying to recreate other apps - maybe Cashew isn't the right choice for you. There are many other budgeting apps out there that may suit your needs better :) Cashew was just an app I made to help myself track my spending in a way that I thought was intuitive.
