### ISSUE TITLE
[Question] [Feature Request] Is there a way to launch a specific search filter? Like transaction filtered via Account Name and month? My Project details in description.

### ISSUE THREAD

**Issue by webpixeldesign** [jameskokoska/Cashew#478]
**Describe your question**
[Enter a clear and concise question about a feature or anything related to the app]

I recently bought NFC tags to automate stuff and do cool things, when I learned we can use NFC embedded in Credit/Debit cards to automate stuff (using it as trigger) using tasker app.

I got an idea and made this figma design quickly, Idea was to launch this
![iPhone 14 Plus - 1](https://github.com/user-attachments/assets/3c4a945e-9710-4aac-9354-7d5cab251bd3) UI designed using tasker and AutoTools app, this will have card specific shortcuts, now when I made this I didn't know what was possible to do and only remembered I read something like deep link in changelog of cashew long back and thought it was possible to do this.

Now after reading github readme, i think we can add transactions easily but can't? launch transaction history with filter pre applied? If that is so, can we please get an option to filter history with deep link?

NOTE TO THE SUBMITTER
**Please check past issues to ensure you are not duplicating questions. Duplicates will not be addressed again.**
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment]
I like the idea, however filters are quite advanced in the way they are stored as a string. They are stored as a string to support memory saving across app sessions - not for applying via an external link. They also use IDs of database entries instead of names for example, so it gets complicated if you want to create a custom filter from scratch. Additionally the formatting is very specific and doesn’t follow any standard (for example it doesn’t follow JSON), they are custom made, so the chance of a broken custom filter is very likely with no specific way to verify its functionality. Additionally it’s difficult to create documentation for a format of this nature. Deep links to other parts of the app are coming in future releases, but it isn’t a priority right now.
