### ISSUE TITLE
[Feature Request] Extra zeroes button

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#49]
..

**Comment by jameskokoska** [comment]
Hi there, that is a great suggestion for inclusivity across locales. Just by looking at the current design of the amount entry screen, there isn't much room/it won't make sense from a grid perspective to add the option - since its based on a calculator format. Open to input - would you have any ideas of how to reformat the amount input?

![image](https://github.com/jameskokoska/Cashew/assets/50821962/4ef4d80d-797c-413e-a7fd-32130638a6ca)

Closing for now, can reopen if changes are needed.

**Comment by ngocanhtve** [comment]
Here's a suggestion about the layout of the three-zero input button:
(https://github.com/jameskokoska/Cashew/assets/125894401/d4c6ff8b-4ad2-41ca-a667-5e266d307334)

**Comment by jameskokoska** [comment]
Thanks for the recommendation, seems like it will hinder the usability and design of the application. You can see in the example you provided, it is quite disorganized and does not have the greatest reachability.

**Comment by ngocanhtve** [comment]
@jameskokoska How about this:
![](https://github.com/jameskokoska/Cashew/assets/125894401/1cc3c7b4-f56e-46d8-9e21-7414fc86a8b6)

**Comment by jameskokoska** [comment]
Sure I can consider adding this, just in a different location. It will be a setting in the app. Would you suggest 3 zeroes or 2 zeroes?

**Comment by ngocanhtve** [comment]
@jameskokoska 3 zeroes, please! Thanks!

**Comment by ngocanhtve** [comment]
It so good! Thank you.
