### ISSUE TITLE
[Feature Request] Consider an option to import data from ivy wallet

### ISSUE THREAD

**Issue by S-Sajith** [jameskokoska/Cashew#496]
Since ivy wallet development is abandoned I am looking into import my data into Cashew, however since I have more than 2 years of transaction data with lots of account transfer data too, it will take a long time to convert the data into the cashew csv template.

So it would be convenient to have an option to directly import the data from either ivy wallet's backup zip or the csv export from ivy wallet

**Comment by jameskokoska** [comment]
CSV import is already supported and a guide can be found in the FAQ: https://cashewapp.web.app/faq.html

The guide addresses the way transfers are imported, which indicates that transfers should be exported as individual transactions in order to support Cashew’s import format (which may be different than the way Ivy handles data - although I am not familiar with the format)

The CSV template provided within Cashew ensures a uniform format when importing data. This is important to support all platform import formats. 

Consider creating or finding a script to convert your data. There is one that I am aware of, albeit for Paisa, that converts Paisa data to Cashew format https://github.com/FosRexx/paisa-to-cashew

**Comment by alphanerdgen** [comment]
> @S-Sajith https://github.com/uderbashi/IvyWallet-Cashew-CSV-Converter

For normies like me, the process between step 2 and 3 is a black hole. What values do I need to add in that script besides the path to the Ivy Wallet CSV file? A step-by-step guide would be very helpful.

cc: @uderbashi

**Comment by iannim** [comment]
I created a script that converts Ivy Wallet’s CSV data into a format compatible with Cashew. I’ve shared it on GitHub, and thought it might be helpful for others in the same situation.

You can find it here: https://github.com/iannim/Ivy2Cashew.
