### ISSUE TITLE
[Bug] Deletion time of categories depends on index in list

### ISSUE THREAD

**Issue by Walnussbaer** [jameskokoska/Cashew#521]
**Describe the bug**
It takes less time to delete a category at the end of the category list than deleting a category at the beginning of the list. 

In other words, if you have a list of categories with category index i starting from 1 ... n

Starting from i = 1, when i is rising, the more time it takes to delete that category. 

**How to reproduce**
Create for example 20 categories. Then compare the deletion time of the newest category with the deletion time of the oldest category. 

**Screenshots/videos**

https://1drv.ms/v/s!ApDzxRPT1717i9MR-hBIlruaxbi4QA?e=TXCS8a

**Details**
 - Device: WebApp running in Firefox on Windows 10
 - App Version: 5.4.0+413

**Additional notes**

**Comment by jameskokoska** [comment]
Yes this is because the app has to run a reorder algorithm when the item is not at the end (of order 0). This is because there is no official way to order items in SQL (it has to keep track manually). Additionally, the web apps performance is very device dependent, an unfortunate result of the Flutter web engine.

**Comment by Walnussbaer** [comment]
> Yes this is because the app has to run a reorder algorithm when the item is not at the end (of order 0). This is because there is no official way to order items in SQL (it has to keep track manually). Additionally, the web apps performance is very device dependent, an unfortunate result of the Flutter web engine.
> 
> The user experience assumes that the user doesn’t delete categories often, so it shouldn’t be a huge issue that needs to be optimized further than the current batch update method.

I'm just curious: why is there a reordering needed if you want to delete something by ID (I suppose this is what's happening under the hood)? 

By the way I don't think my system is the problem here, running a Ryzen 9 5900x :D

**Comment by jameskokoska** [comment]
Each entry that can be reordered has an order number assigned to it, since the user can set a custom order for categories, goals, etc. When one is deleted, all the elements below the order need to be updated too (i.e. “shifted” to fill the remaining space. Take for example this order 1,2,3,4,5 if we delete element 5 it’s easy just remove 5, but if we delete element 1, the elements with order number 2,3,4,5 need to subtract one to become 1,2,3,4. Cashew orders things in reverse, that’s why elements at the bottom of the list don’t need to be updated the new order number. This is because when recommended titles get added, they get added to the top to prevent all the ones below from being shifted - increasing efficiency when adding a new element - especially for titles which can accumulate. This code was written a while ago - there’s probably some optimizations but it uses batch writing (if I remember correctly) it just has to update multiple elements for a reorder/deletion. Hope this gives some insight.

**Comment by Walnussbaer** [comment]
> Each entry that can be reordered has an order number assigned to it, since the user can set a custom order for categories, goals, etc. When one is deleted, all the elements below the order need to be updated too (i.e. “shifted” to fill the remaining space. Take for example this order 1,2,3,4,5 if we delete element 5 it’s easy just remove 5, but if we delete element 1, the elements with order number 2,3,4,5 need to subtract one to become 1,2,3,4. Cashew orders things in reverse, that’s why elements at the bottom of the list don’t need to be updated the new order number. This is because when recommended titles get added, they get added to the top to prevent all the ones below from being shifted - increasing efficiency when adding a new element - especially for titles which can accumulate. This code was written a while ago - there’s probably some optimizations but it uses batch writing (if I remember correctly) it just has to update multiple elements for a reorder/deletion. Hope this gives some insight.

Ah I see, thank you for the explanation! :)

**Comment by jameskokoska** [comment]
It could be, but for optimized database reads with SQL using a sortby order is the most optimal approach.

**Comment by Walnussbaer** [comment]
> It could be, but for optimized database reads with SQL using a sortby order is the most optimal approach.

I see. And I guess, reading is more important in that case than writing, because one does not delete a category every day. All right, thank you for the short exchange!
