### ISSUE TITLE
[Bug] Add transaction popup stretched out

### ISSUE THREAD

**Issue by awwRoar** [jameskokoska/Cashew#539]
**Describe the bug**
The Add transaction pop-up appears vertically stretched out at times (please see screenshot below). It isn't seen every time, I noticed it mostly when I long press on a calendar date to add a transaction.

**How to reproduce**
Click on the + to add an entry or Long press on a date in the calendar section to add a transaction and wait for the popup. Didn't always happen.

**Screenshots/videos**
![1733118391748](https://github.com/user-attachments/assets/cf151aa7-410a-41b7-b0df-dc0aa500ff57)

**Details**
 - Device: Redmi Note 11
 - App Version: v5.4.4+420

**Additional Notes**
Bug can't be reproduced at all times. I tried figuring out if it follows something but I can't point to anything such, it appeared randomly over the past few weeks since I started using Cashew. However when I tried to reproduce it this morning and record to share it here, it didn't reappear.

**Comment by jameskokoska** [comment]
Yea this is a known bug of the over scroll stretch for Android platforms. In Cashew is appears when the keyboard pops up with significant velocity on a constrained scroll view. Cashew attempts to fix this be calculating a resize after the popup, however it doesn’t always fix the issue. 

Since this is primarily related to the over scroll stretch in the Flutter engine, please submit a minimal reproducible example on that repository.
