### ISSUE TITLE
[Feature Request] Suggestion: Add PostgreSQL Support or Provide Guidance to Implement

### ISSUE THREAD

**Issue by luansilvadb** [jameskokoska/Cashew#540]
**Is your feature request related to a problem? Please describe.**

I’ve been using Cashew and love its features, but I’ve noticed some issues with data synchronization across devices. There are times when data discrepancies occur, likely due to the current database setup (Firebase + SQLite). A more robust relational database, like PostgreSQL, could resolve this by providing centralized, consistent, and reliable data handling.

**Describe the solution you'd like**

I’d like to propose adding PostgreSQL as a database option. This could address the synchronization issues by offering:

A single source of truth for all devices.
Consistent and reliable data management across multiple devices.
Advanced query capabilities and better scalability for larger datasets.

**Describe alternatives you've considered**

Manually integrating PostgreSQL on my own, but I’d need guidance to ensure it aligns with the app's architecture.

PostgreSQL could complement the current setup by offering more flexibility. If this doesn’t align with the project goals, I’d appreciate guidance or suggestions on implementing it myself.

**Cheers,
Luan**

**Comment by jameskokoska** [comment]
There are no plans on supporting another database type. The Cashew application uses a local SQLite to track information.

One of the main reasons for inconsistent syncing is because of a lack of truth. Cashew merges changes together rather than one centralized source of truth. This is because Cashew’s data is all stored locally on each device and is not uploaded to any centralized cloud platform.
