### ISSUE TITLE
[Feature Request] Link Expenses with Reimbursements or Related Income

### ISSUE THREAD

**Issue by teipa056** [jameskokoska/Cashew#545]
**Is your feature request related to a problem? Please describe.**
Currently, the app doesn’t allow transactions to be linked, which can make the monthly budget appear inaccurate in scenarios involving reimbursements or shared expenses. For example, if I incur a medical expense of 100€, and later receive an 80€ reimbursement, my budget still reflects a 100€ expense instead of 20€. Similarly, if I pay 150€ for a group dinner and get reimbursed by friends, it shows a higher expense than what I ultimately incurred.

**Describe the solution you'd like**
I would like the ability to link transactions together. This would allow one or more income transactions (like reimbursements) to be associated with specific expense transactions. The app would then reflect the net impact on the budget. For example:

Expense: 100€
Reimbursement: +80€
Net impact on budget: 20€
This feature could be implemented as a linking system where users can create relationships between transactions, indicating that one offsets or partially offsets another.

**Describe alternatives you've considered**

- I could theoretically first add the expense (100€) and afterwards when I get the reimbursement I would simply ignore it and instead update the expense to 20€. My issue with this method is that, for my child, I get 100% reimbursed, so I would need to actually delete the medical expense but I still want to track the expense so that in the future I could come back and see when we went to the doctor.

- Another alternative would be for me to simply exclude medical expenses from my budget but once again it would not be accurate.

**By the way, thank you for creating such an amazing application. I've always wanted to create one myself, but never had the time, and this app is the closest I've come to what I'd expect from a budget app.**

**Comment by jameskokoska** [comment]
You can use long term loans to group multiple related transactions towards a common total. Loans can be included in budgets.

**Comment by fravel77** [comment]
Can we please reopen this ?
Topic is still partial refund, typical for example for medical expenses o slightly defected goods.
I am ok to handle this with the Long Term Loan concept. It is great I can see in one shot the percentage of reimbursed money.
The part that will be never refunded (it is a partial redund) it is shown as Lent Money, below (and besides :) ) Expenses and Income. I can be ok also with that.

In this way I will have several Long Term Loan that will be never completely refunded. When I know that the (partial) refund is completed then I will need to Archive the Long Term Loan, in order to not have them always in front in the add transaction mask.

The issue here is that once I archive it the "Lent Money" voice will disappear from the summary of the voices which contributes to the Net Total and Account Total.

So for example I have, for a certain time range:

**Net Total: €200

Income; € 500
Expense: € 200
Lent:  € 100 (consider this as the part of payment that will never be reimbursed)**

Now if I archive the Long Term Loan with this € 100 pending I will have:

**Net Total: €200

Income; € 500
Expense: € 200**

I have no visibility of the additional € 100 euro which count anyway as expense even if they are Lent MOney.

Is there a way to keep showing there the Long Term Loan if not completly repaid and even if archived ?

**Comment by fravel77** [comment]
I have found another weird (at least from my point of view) aspect of how the Long Term Loan are handled.
If I go to "All Spending", I can see that the entire initial sum paid as Loan is displayed as expenses. And the reimbursement part is displayed as income.
For example i have 600 euro of medical expenses and my insurance reimbursed me just 500.
In the expenses summary (also in the pie chart) i can see 600 euro of expenses in my "Health" category....and 500 as income...still in "health" category. 
When I see at the expenses, pie chart included, I would like to see already the netto I paid.

netto = Initial Payment - Refunded sum

This is telling me what I have really spent for the category "Health". In this case just 100 euro.
That 600 euro just for Health expenses inflate too much the expenses of that category, it is not giving immediately the info I need.

**Comment by AlessandroKuz** [comment]
> Can we please reopen this ? Topic is still partial refund, typical for example for medical expenses o slightly defected goods. I am ok to handle this with the Long Term Loan concept. It is great I can see in one shot the percentage of reimbursed money. The part that will be never refunded (it is a partial redund) it is shown as Lent Money, below (and besides :) ) Expenses and Income. I can be ok also with that.
> 
> In this way I will have several Long Term Loan that will be never completely refunded. When I know that the (partial) refund is completed then I will need to Archive the Long Term Loan, in order to not have them always in front in the add transaction mask.
> 
> The issue here is that once I archive it the "Lent Money" voice will disappear from the summary of the voices which contributes to the Net Total and Account Total.

**Can we please reopen this issue?**
I agree tha the topic of partial refunds (e.g., for medical expenses or friends reimbursments) is still not fully addressed.

I appreciate the flexibility of using Long Term Loans to track reimbursements and see the percentage of refunded money at a glance, but i dont like that for partial ones you're not able to archive properly...

**Comment by therealVitia** [comment]
hey, sorry for making a duplicate feature request for this, I didn't see that it already existed ! 
I agree with all previous statements that the loan feature isn't really a great solution for the issue that we all have here. Especially since loan are all grouped up together in a way that makes it really hard to sort through. 

In a case where I pay for a group of 5 people, I would have to first divide the transaction into 5 and add 1/5 of the expense for me, and then create 4 separate loans in the loans tab so I can follow how many people gave me my money back. 

This is quite a long and tedious process, and I especially like this app for its ability to make the expense tracking process quick and easy to do. 

Please reopen this issue !

**Comment by aitor-gamarra** [comment]
Hi @jameskokoska !

Sorry for the mention, would you be open to re-open (pun not intended) this issue? I agree with the previous comments, paying for a group is a pretty common situation and a lot of people seem to be interested in this feature.

I find that in my usual spending I have "actual transactions" and "logical transactions". From @therealVitia 's example, I would have a "dinner" logical transaction of let's say 20$, and then inside that, 5 "actual transactions". So in Cashew, I'd see:

- Dinner (`-20$`):
  - `-100$` transaction paying for the whole dinner (category: dinner).
  - `+20$` transaction (reimbursement from friend 1).
  - `+20$` transaction (reimbursement from friend 2).
  - `+20$` transaction (reimbursement from friend 3).
  - `+20$` transaction (reimbursement from friend 4).

So, in the end, my reporting for the month would say:

- Dinner Category: `-20$`

At this point it's not that important (for me at least) who reimbursed me, it can be added as a note.

This is just an example but I think it's a pretty common thing (paying something and being reimbursed in purchases and returns, going out with friends, insurance...).

Hope it makes sense, and thanks for developing Cashew :)
