### ISSUE TITLE
[Feature Request] Account Specific Categories

### ISSUE THREAD

**Issue by Rcarballo2222** [jameskokoska/Cashew#553]
**Is your feature request related to a problem? Please describe.**
When adding a transaction and selecting a category, all accounts come up as ones I can assign the transaction to. This can be a bit challenging for enforcing certain categories only belong to specific accounts (ex: I don't want to accidentally log an entertainment transaction in my Business account)

**Describe the solution you'd like**
I'm looking for something like Money Lover's implementation of categories. Each account has a setting where you can select which categories are enabled for it. So ideally when I'm adding a transaction and select a category, only the accounts with that category enabled can be selected

**Describe alternatives you've considered**
Being very cautious to always select the right account when I select a category. This can work, but if I'm adding a transaction quickly it's prone to errors, or for less obvious categories It might be confusing or difficult to remember which account I wanted those types of transactions to be in.

Thanks!

**Comment by jameskokoska** [comment]
Thanks for the suggestion! It's an interesting idea, however I don't think it fits in well in Cashew. Categories are meant to categorize all transactions within Cashew. Categories should be available for all accounts - in my opinion it's hard to justify an extra layer of categorization and possible confusion for account specific categories. It's not always intuitive for users when some categories only appear after selecting an account. Categories should be able to be applied to any transaction.

**Comment by jameskokoska** [comment]
To add on, this becomes even more difficult to justify after the next update which will support a customizable add transaction experience. See screenshot below:
![image](https://github.com/user-attachments/assets/bbcedc08-7c21-418e-acb2-921f9f9f557e)

**Comment by Rcarballo2222** [comment]
Thanks for the quick response! 

What if the order was category and then account? Like basically when you select a category, the accounts you can add it to get "filtered" so only the applicable ones remain? By default all categories could be enabled on all accounts so there wouldn't be any confusion for users that aren't explicitly using the setting.

By the way, the customizable add transaction flow looks awesome, excited to try that!

**Comment by jameskokoska** [comment]
I can definitely keep it in mind and it's an interesting feature but I think it'll be in the back burner for now - I just don't think the overhead is worth the complexity, it's quite a niche feature (IMO), and it does add quite a bit of user experience complexity and explanation (which isn't the main goal of Cashew). There are many other budget apps out there with many many more tracking features that Cashew will just never have; because Cashew's goal is to be a simple, efficient, and straightforward financial management tracking tool.

**Comment by resnard** [comment]
I really like the idea of assigning an account to a category by default.

Can't it be implemented in a way that simply bases the initial selected account in a specific transaction category on the previously used account with the same transaction category?

The point is to not filter the account option but simply set the initial selected account when adding a transaction based on the first previous similar transaction category (not exceeding 5 years)

This way, users can still change the account used manually.

And if the category has no transacton record or it's been 6 years since it has been recorded, it defaults back to the active account on the homepage.

Will make it faster to add transactions on categories that the user have a dedicated account for, when that category has a recent transaction record. All that, without having to switch out from their go to account for spending/saving.
