### ISSUE TITLE
[Feature Request] Added attachments as list item

### ISSUE THREAD

**Issue by jrom99** [jameskokoska/Cashew#57]
**Is your feature request related to a problem? Please describe.**
Whenever I add an attachment to a transaction, an URL appears within its notes. It is somewhat bothersome considerong the same URL is also below in a neat format.

**Describe the solution you'd like**
Any attachment should be displayed only as a list item (as it already looks like), but without the URL polluting the notes.

**Describe alternatives you've considered**
I haven't considered other alternatives.

**Additional context**

Screenshot showind data duplication:
![Screenshot_2023-11-29-21-17-03-196-edit_com.budget.tracker_app.jpg](https://github.com/jameskokoska/Cashew/assets/47498278/feaf73d2-bce8-41ac-a478-79cd538f085f)

NOTE TO THE SUBMITTER
Not all feature requests will be considered. This budget app was created with careful thought given to each feature's usability and prevention of feature overload. As you use the app, you will discover possibly related useful features and that may not be obvious right away. 
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jrom99** [comment]
Slightly security concern, it seems the URL can be opened without logging in to my account, does that mean that any attachments I use are actually made publicly available?

**Comment by jameskokoska** [comment]
Added here: https://github.com/jameskokoska/Cashew/commit/dc36a6c8bf38e899186f1cab418a571fe3af7c58

Links have been cleaned up and included in the notes section in a better way. Going to keep them there in case users ever want to edit a link, it will be easier

Permissions was an oversight. Thanks for catching that! I thought it was needed to generate a shareable link, turns out this is not the case. No longer creates shareable links, the account owner is the only one with permissions 
Fixed here: https://github.com/jameskokoska/Cashew/commit/dc36a6c8bf38e899186f1cab418a571fe3af7c58#diff-70f95526de7ecc9ea1fefeff1c508fc890d001878e17c8ac6b1f6f47f7de2d32L204
Since it is attached the users Google Drive account, the user can change the permissions if they wish within Google Drive.

![image](https://github.com/jameskokoska/Cashew/assets/50821962/8a7b93b1-e9fa-4dba-bcb2-dd654402076e)
