### ISSUE TITLE
[Feature Request] Share budgeting with my family/spouse

### ISSUE THREAD

**Issue by spoctoss** [jameskokoska/Cashew#61]
**Is your feature request related to a problem? Please describe.**
My wife and I do our budgeting together manually and there doesn't seem to be a good way for us to share the added transactions and budget progress easily.

**Describe the solution you'd like**
I would like to be able to have my added transactions budget changes and full account details be synced and shared between my device and my wife's 

**Describe alternatives you've considered**

**Additional context**
[Add any other context or screenshots about the feature request here.]

NOTE TO THE SUBMITTER
Not all feature requests will be considered. This budget app was created with careful thought given to each feature's usability and prevention of feature overload. As you use the app, you will discover possibly related useful features and that may not be obvious right away. 
Feel free to email me at dapperappdeveloper@gmail.com and I'll be happy to help you!

**Comment by jameskokoska** [comment]
Edit: An answer is highlighted in the FAQ https://cashewapp.web.app/faq.html#syncing-with-multiple-users

The only way to do this would be to share a Google account and use the syncing feature. Servers are expensive, privacy concerns and syncing with other users creates many problems and is outside the scope of this app. Also, I don’t want to be responsible for handling/managing/storing any user’s financial data. This data should be kept personal to the user, and the average user should fully understand how their data is handled. This one of the goals of Cashew. A personal Google account is trusted and users understand who is handling offloaded data. On top of this: the app uses an internal relational database because of this relational architecture, it does not easily support collection syncing. Without an external third party middle server implementation, data cannot be incoming in realtime as we cannot emulate a live collection from a server.

If this feature is really important to you, I would recommend another app. There are many apps that are architected around sharing data with other users. Sorry about that!

Edit: Added technical details and architectural design choices

**Comment by spoctoss** [comment]
Would giving some control to where in google drive the data is stored and allowing the ability to select a shared folder inside google drive with another user be a way to accomplish this?

**Comment by jameskokoska** [comment]
That's an interesting idea, in theory it could be possible. It would require major refactoring of how the sync system functions though. Currently the way the application stores its data is through [application specific data](https://developers.google.com/drive/api/guides/appdata) which is only ever tied to one Google account.

Another issue is that the syncing feature, although useful, can sometimes become out of sync and the best choice of action is to restore a sync point/backup. So I don't want users to rely on this feature too heavily especially across accounts and users where data is more spread out.

**Comment by fabinou** [comment]
Hello

I needed the same thing, what i have done so far is creating a third account, and add this one on the two devices, at least i don't sync anything else than this

**Comment by OmkoBass** [comment]
James I know that you are a solo developer here and it would take lots of refactoring. Maybe you could make a self-hosted option where we can connect to our own server that will sync and handle the requests.

I bought lifetime access to this app as soon as I saw it but I also need to track the expenses of my whole family and if that will never be implemented then that's a huge disappointment. It's going to really hard leaving this app for something else but a sharing feature (user's server, not your own) is a must if you want to compete with others.

P.S. you could compete with others, Cashew is the best software I have ever used for budgeting and tracking.

**Comment by HoLengZai** [comment]
> James I know that you are a solo developer here and it would take lots of refactoring. Maybe you could make a self-hosted option where we can connect to our own server that will sync and handle the requests.
> 
> I bought lifetime access to this app as soon as I saw it but I also need to track the expenses of my whole family and if that will never be implemented then that's a huge disappointment. It's going to really hard leaving this app for something else but a sharing feature (user's server, not your own) is a must if you want to compete with others.
> 
> P.S. you could compete with others, Cashew is the best software I have ever used for budgeting and tracking.

Hi @OmkoBass, @fabinou, @jameskokoska 
I read the FAQ and they mentioned the third account for sharing budget but I would like to know how it works for sharing with my family/spouse and then combining it with lifetime access. Does it mean I need to buy lifetime access through that third/shared account?
Or I can pay with my main account and sync the data through the third/sharing account hence my wife will get the most recent data and can contribute to the app?
Thanks
