### ISSUE TITLE
[Bug]bill splitter

### ISSUE THREAD

**Issue by Darchiver** [jameskokoska/Cashew#69]
1.When we try to set amount in bill splitter , the amount is taken as percentage only.
https://github.com/jameskokoska/Cashew/assets/121549490/0600b140-457f-4066-bf5d-e7bc3563fd12

2.even though if we enter the percentage, the percentage can be set more than 100% which can mess up with the calculation
https://github.com/jameskokoska/Cashew/assets/121549490/48bb89e4-88d7-4949-b933-fc246b6596bf

**Comment by jameskokoska** [comment]
The way the bill splitter functions is that it only takes percentages. If you know the amount someone is spending, no need to split the bill and calculate it. Add a new entry with 100% of what someone owes.

The splitter is not going to limit the percentages you input. However, it is working as intended, since you entered a number above 100% it shows up in red that the total was not achieved properly.
