### ISSUE TITLE
[Feature Request] Create repetitive transactions for a year in advancr

### ISSUE THREAD

**Issue by Jakopt** [jameskokoska/Cashew#88]
Currently repetitive transactions are only created for their next occurence. It would be a lot more helpful for planning if I could see the repetitive transactions further than that. The best solution would obviously be to create the future transaction "on demand" when they are need for a graph or statistoc etc., but just creating them for a year in advance would already be very helpful.

Thanks for all the work you put into this app.

**Comment by jameskokoska** [comment]
Thank you for the suggestion! Unfortunately the way the upcoming transactions are coded in, it doesn't support this right now. The main reason being it would create a lot of clutter if transactions are created far in advance. There would be many interaction issues such as: how would they be edited, deleted etc. If they are created one by one, it makes the app's functionality and usability clear and concise.

**Comment by jsrol** [comment]
I really love your app but I suggest giving another thought on this. Not trying to start an argument, just to let you know where I come from and you can do what you will with this info: 

Imagine how confusing it would for reccuring meetings in a calendar app like Outlook to not show up in your calendar until the previous one has been completed. It would make it impossible to plan ahead because you'd never know if the gap in your schedule is actually a gap or not without backtracking and looking at all your recurring meetings.

The same thing happens here but the schedule gaps are now monthly budget gaps. I am unable to plan ahead on my budget because i will never know what payments are going to pop up next month, heck even next week. I cannot prepare a larger expense in a month with a low recurring expense total for example. I cant offset the worse months because i dont know which ones it'll be. Plus, it makes some statistics useless. For example the "upcoming" stat on the dashboard shows 8 transaction with a total of $1.2k. However, 3 of those transactions are recurring every 2 weeks, some every 6 months, other ever 2 months, etc. so the actual total is 90+ transactions for $20+k for the year. So okay, i guess i dont need the entire year of transaction, but why would it make sense for "upcoming" to include a transaction due in september, but the one in 3 week from my 2nd paycheck of the current month isnt included? I don't see how this data is anything else than misleading in its current form.

It makes the app great at historically logging your expenses but not planning them!

As to the issues you mention. Couldn't it work by just having them all "linked" together so editing one edits all minus past ones, or deleting one deletes all (again, minus past ones)? In calendar apps it works like that and you can also decide on edit and deletion if you want to delete all or just the selected one.  Also regarding "clutter" i suggest leaving it to the users to decide with a toggle filter. 


Peace!

**Comment by sevenate** [comment]
I concur with @jsrol as the example with Outlook is very informative. It would probably also yield a lot of work (or re-work) to implement this feature properly (Outlook's recurring events style), may be it could be "worth" a dedicated tab/section in the app. This should also expand the potential target audience of the app as currently you really can only track your _past_ expenses (and income), but can't do much about planning your _future_ transactions.

**Comment by jameskokoska** [comment]
I get that it can be difficult to understand. The calendar analogy is great and I have already considered this approach when designing the app. Unfortunately the way the app's architecture works, I can't think of a way to implement it this way. There are insights similar to what you describe on the subscriptions page: the app can extrapolate totals averaging through months/years based on the repetition amount.

If needed you can always create the transactions for all the future, marking them all as paid (set the setting 'Paid Date' to 'Transaction Date' and mark the transactions as paid to create entries on those days for insights)

I think one of the main issues is that the way transactions are read from the database are single entries at a time. This makes working with SQL queries great for totaling amounts. The app can 'imagine' upcoming transaction entries in the UI, but it would be very difficult to implement this, how would it know an upcoming transaction is scheduled on this day? for example. Also, totaling potentially upcoming rows for insights into upcoming transactions that don't yet exist in the database would be very difficult. Cashew cannot just create an 'infinite' amount of entries in the db, this makes reads for totaling add up to infinity given current calculations and if something was to change with a transaction, updating or deleting these 'infinite' entries isn't viable.
