### ISSUE TITLE
[Feature Request] Align the save changes button

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#90]
![IMG_20231220_180548_976](https://github.com/jameskokoska/Cashew/assets/125894401/b2d2929a-69a0-40fb-b03d-2a2bc5d43be3)

This is the **save changes** button. Off to the bottom and too close to the two sides of the screen. Very unbalanced.

![IMG_20231220_180551_686](https://github.com/jameskokoska/Cashew/assets/125894401/c281cd93-a703-491d-94fd-315d40bfd778)

I suggest re-aligning it to look like the **set amount** button as shown above. Perfectly balanced.

**Comment by jameskokoska** [comment]
Thanks for the details!

Since the bottom padding is set by your device (the bottom safe area - could occur from a gesture navigation bar) it is pushed as far to the bottom as possible. On devices without a bottom gesture bar, or one that is hidden, the button is pushed to the bottom and does indeed look balanced.

I don't want to add extra bottom padding on devices with safe area of zero, as that button takes up valuable screen real-estate when on the add pages (Since the important information is shown in the page and the button is always stuck to the bottom)

You can see here on a device without a bottom safe area:
![image](https://github.com/jameskokoska/Cashew/assets/50821962/62b2192a-2def-46d7-bca7-5782d1058cfd)

**Comment by ngocanhtve** [comment]
![Screenshot_20231221-125325_Trebuchet](https://github.com/jameskokoska/Cashew/assets/125894401/4d7096a8-af90-4b16-9cb5-af1cfeb54350)

No sir, i'm not talking about the bottom edge of the screen, i'm talking about the padding on the two side of the screen.

If you redraw the padding of **save changes** button to be similar to the padding of the **note area**, it will look very balanced. Not about bottom edge.

**Comment by ngocanhtve** [comment]
@jameskokoska I mean like this, to keep the balance between the **save button** and the **notes area**:

![Screenshot_20231221-125325_Trebuchet](https://github.com/jameskokoska/Cashew/assets/125894401/27501890-1ab1-4bcd-b3e4-289b40772bb2)

Or like this if is subscription, to keep the balance between the **save button** and the **pay button**:

![Screenshot_20231221-134142_Trebuchet](https://github.com/jameskokoska/Cashew/assets/125894401/e75d88c1-91f4-4902-90a8-a4d68236f54a)

So maybe I should rename the request to **Padding the save changes button** instead of **Aligning the save changes button**.

**Comment by jameskokoska** [comment]
I think that when the bottom buttons are fully aligned with the edges of the screen, it looks the best. Especially for a sticky button located at the bottom of the page where we are trying to avoid it taking screen real estate. The reason the 'Pay' button (or action items) take up a smaller portion of the screen is because it is not the primary action of the bottom sticky button.

**Comment by ngocanhtve** [comment]
@jameskokoska 
> I think that when the bottom buttons are fully aligned with the edges of the screen, it looks the best.

Agree.

> Especially for a sticky button located at the bottom of the page where we are trying to avoid it taking screen real estate.

Agree. But please make 'border-radius' of the rounded corners on the red dots more uniform. And I find the rounded corner of the **note** area has the most perfect curve.

![Screenshot_20231223-093809_Trebuchet~2](https://github.com/Costeer/Gruvbox-Material-Themes/assets/125894401/9edca61e-67f4-4133-9a2e-a2b860b27bd7)

> The reason the 'Pay' button (or action items) take up a smaller portion of the screen is because it is not the primary action of the bottom sticky button.

Agree.
