### ISSUE TITLE
[Feature Request] Align the left margin and right margin

### ISSUE THREAD

**Issue by ngocanhtve** [jameskokoska/Cashew#98]
The date line and transactions line are not aligned on the left and right edges.

![Screenshot_20231226-113213_Trebuchet~5](https://github.com/jameskokoska/Cashew/assets/125894401/9f41b270-f6bf-4ca8-bc5e-d715239e3839)
![Screenshot_20231226-113213_Trebuchet~3](https://github.com/jameskokoska/Cashew/assets/125894401/06c64b7a-92e7-4b9c-b043-ed045b97df95)

Please align them properly.

**Comment by jameskokoska** [comment]
Please provide more information and follow the feature request template provided.

**Comment by ngocanhtve** [comment]
@jameskokoska You mis the update!

**Comment by jameskokoska** [comment]
Thank you for providing more information. In the future please use the provided template. Please also stop mentioning my username.

To address your concern, since it is a subheader, the padding is less than on the transaction entry. This is to visually show separation in the UI.

Therefore, an intentional design.

**Comment by ngocanhtve** [comment]
> Therefore, an intentional design.
I know it's a intentional design. But please think again another method using color or border instead of padding.

Now color also helps separated. Padding makes the information of transaction lines that do not have enough display space become even more lacking when there is too much padding.

For example, lines that are associated with subcategories the trail of the sub-category will be hidden, information will be missing.
